In [2]:
!pip install pandas pycountry-convert

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: pycountry-convert in /opt/anaconda3/lib/python3.12/site-packages (0.7.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: pprintpp>=0.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (0.4.0)
Requirement already satisfied: pycountry>=16.11.27.1 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (24.6.1)
Requirement already satisfied: pytest>=3.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (7.4.4)
Requirement already satisfied: pytest-mock>=1.6.3 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (3.14.0)
Requirement already satisfied: pytest-cov>=2.5.1 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (6.0.0)
Requirement already satisfied: repoze.lru>=0.7 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (0.7)
Requirement already satisfied: wheel>=0.30.0 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (0.43.0)
Requirement already satisfied: iniconfig in /opt/anaconda3/lib/python3.12/site-packages (from pytest>=3.4.0->pycountry-convert) (1.1.1)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from pytest>=3.4.0->pycountry-convert) (23.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in /opt/anaconda3/lib/python3.12/site-packages (from pytest>=3.4.0->pycountry-convert) (1.0.0)
Requirement already satisfied: coverage>=7.5 in /opt/anaconda3/lib/python3.12/site-packages (from coverage[toml]>=7.5->pytest-cov>=2.5.1->pycountry-convert) (7.6.8)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
# imports
import pandas as pd
import warnings
import pycountry_convert as pc
warnings.filterwarnings("ignore", category=FutureWarning)
pd.set_option('display.max_rows', None)
electricity_data = pd.read_excel('../Original Data/Electricity Prices Europe.xlsx', sheet_name=2)

In [4]:
electricity_data

,Area,2017-S1,2017-S2,2018-S1,2018-S2,2019-S1,2019-S2,2020-S1,2020-S2,2021-S1,2021-S2,2022-S1,2022-S2,2023-S1,2023-S2,2024-S1
0,GEO (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,European Union - 27 countries (from 2020),0.1271,0.127,0.1286,0.1329,0.1282,0.1280,0.1269,0.1282,0.1341,0.1515,0.1934,0.2401,0.2393,0.2226,0.2187
2,"Euro area (EA11-1999, EA12-2001, EA13-2007, EA...",0.1327,0.132,0.1346,0.1390,0.1335,0.1332,0.1332,0.1356,0.1404,0.1577,0.1999,0.2449,0.2607,0.2423,0.2378
3,Belgium,0.1929,0.179,0.1872,0.1976,0.1948,0.1954,0.1872,0.1798,0.1767,0.2015,0.2622,0.3791,0.3592,0.2793,0.2405
4,Bulgaria,0.0796,0.0819,0.0816,0.0838,0.0831,0.0798,0.0831,0.0818,0.0853,0.0909,0.0911,0.0956,0.0948,0.0993,0.0989
5,Czechia,0.1176,0.1218,0.1286,0.1299,0.1238,0.1255,0.1321,0.1283,0.1284,0.1498,0.1879,0.2077,0.2624,0.2582,0.2574
6,Denmark,0.094,0.0922,0.1011,0.1116,0.1084,0.1042,0.0951,0.0908,0.104,0.1485,0.2371,0.3636,0.2976,0.1846,0.1883
7,Germany,0.1389,0.1383,0.1379,0.1378,0.1473,0.1321,0.1430,0.1451,0.1562,0.1596,0.1899,0.2333,0.2973,0.2882,0.2806
8,Estonia,0.0926,0.095,0.0989,0.1048,0.0982,0.1027,0.0882,0.0953,0.098,0.1493,0.159,0.2085,0.1666,0.1826,0.1769
9,Ireland,0.1846,0.1865,0.1846,0.2006,0.2027,0.2130,0.2037,0.2179,0.2069,0.242,0.2693,0.3823,0.4514,0.459,0.3856
10,Greece,0.1139,0.109,0.1132,0.1125,0.1141,0.1189,0.1285,0.1278,0.1305,0.1588,0.295,0.4556,0.1876,0.1905,0.1827
11,Spain,0.1805,0.1712,0.1873,0.1947,0.1326,0.1287,0.1178,0.126,0.1358,0.1878,0.2579,0.2966,0.2165,0.2068,0.1841
12,France,0.1089,0.1132,0.1134,0.1168,0.1148,0.1260,0.1242,0.1292,0.1289,0.1356,0.1566,0.1723,0.1893,0.2161,0.2187
13,Croatia,0.1011,0.1012,0.102,0.1028,0.1028,0.1030,0.1012,0.1017,0.1003,0.1022,0.106,0.117,0.117,0.1171,0.1167
14,Italy,0.1322,0.1326,0.1285,0.1416,0.1432,0.1427,0.1382,0.1331,0.1432,0.176,0.2671,0.3192,0.323,0.2565,0.2451
15,Cyprus,0.1454,0.142,0.1445,0.1745,0.1545,0.1576,0.1497,0.1184,0.1276,0.1451,0.1693,0.2551,0.2312,0.2099,0.2106
16,Latvia,0.1043,0.1039,0.1035,0.1041,0.1136,0.1144,0.0996,0.1005,0.1024,0.1402,0.1779,0.2448,0.2521,0.2497,0.2261
17,Lithuania,0.0783,0.0777,0.0771,0.0771,0.0947,0.0947,0.1111,0.0972,0.1003,0.1122,0.1205,0.2007,0.2407,0.1919,0.1914
18,Luxembourg,0.1167,0.117,0.1283,0.1302,0.1326,0.1325,0.1465,0.1465,0.1467,0.1468,0.1673,0.1696,0.3012,0.2875,0.3024
19,Hungary,0.0886,0.0893,0.0885,0.0880,0.0882,0.0864,0.0812,0.0794,0.0795,0.079,0.0746,0.0853,0.0911,0.0891,0.0861
20,Malta,0.125,0.1221,0.1209,0.1230,0.1214,0.1227,0.1208,0.1224,0.1209,0.124,0.1221,0.1208,0.1186,0.1203,0.1181
21,Netherlands,0.1146,0.1152,0.1187,0.1212,0.1357,0.1359,0.1379,0.1365,0.1351,0.1493,0.2187,0.3197,0.4436,0.2659,0.2899
22,Austria,0.1221,0.1218,0.1232,0.1265,0.1316,0.1349,0.1358,0.1384,0.1394,0.1448,0.1579,0.209,0.2691,0.299,0.2946
23,Poland,0.096,0.095,0.0906,0.0889,0.0898,0.0867,0.0926,0.0953,0.0921,0.0882,0.0912,0.1003,0.0918,0.1164,0.1065
24,Portugal,0.1106,0.108,0.1007,0.1028,0.1181,0.1204,0.1139,0.1138,0.1131,0.1164,0.1688,0.1972,0.2983,0.2012,0.1823
25,Romania,0.0871,0.0945,0.099,0.0964,0.0983,0.1025,0.1045,0.104,0.1115,0.1167,0.1779,0.2683,0.1435,0.1441,0.1392
26,Slovenia,0.1104,0.1105,0.1108,0.1125,0.1125,0.1146,0.1063,0.118,0.1153,0.1185,0.1023,0.1533,0.1614,0.1614,0.1684
27,Slovakia,0.0832,0.0838,0.0942,0.0849,0.0962,0.0969,0.1074,0.1106,0.1057,0.102,0.1242,0.1315,0.1322,0.123,0.125
28,Finland,0.1049,0.1064,0.1074,0.1144,0.1173,0.1201,0.1178,0.1205,0.12,0.1259,0.1335,0.1806,0.1934,0.1712,0.1763
29,Sweden,0.1257,0.1305,0.1202,0.1320,0.1297,0.1316,0.1200,0.1271,0.134,0.1733,0.1815,0.2489,0.1784,0.1407,0.1571
30,Iceland,0.1263,0.12,0.1222,0.1152,0.1131,0.1132,0.1061,0.0988,0.107,0.1095,0.1205,0.122,0.1208,0.1274,0.1345
31,Liechtenstein,0.1456,0.1367,0.1651,0.1690,0.1710,0.1765,0.1823,0.1791,0.1786,0.1829,0.1898,0.1999,0.3888,0.3174,0.2811
32,Norway,0.1163,0.1137,0.1254,0.1382,0.1360,0.1264,0.0954,0.0927,0.1326,0.1752,0.2005,0.2751,0.1683,0.1521,0.1579
33,United Kingdom,0.1344,0.1344,0.1347,0.1401,0.1450,0.1512,0.1532,:,:,:,:,:,:,:,:
34,Bosnia and Herzegovina,0.072,0.0724,0.0722,0.0729,0.0729,0.0728,0.0721,0.0746,0.0721,0.0714,0.0733,0.0738,0.0742,0.0717,0.0724
35,Montenegro,0.0804,0.0806,0.0828,0.0829,0.0834,0.0847,0.0811,0.0821,0.0807,0.0803,0.0792,0.0809,0.0845,0.0846,0.0894
36,Moldova,0.0977,0.1013,0.102,0.0960,0.0936,0.1019,0.1068,0.0993,0.0851,0.0888,0.1047,0.1976,0.1795,0.1469,0.1359
37,North Macedonia,0.0695,0.0687,0.0662,0.0667,0.0664,0.0669,0.0662,0.0706,0.0713,0.08,0.0895,0.0981,0.0957,0.0982,0.0943
38,Georgia,:,:,0.058,0.0628,0.0686,0.0524,0.0562,0.0482,0.0535,0.0559,:,0.0716,0.0718,0.0733,0.0602
39,Albania,0.0703,0.0713,:,0.0759,0.0767,0.0778,0.0768,0.0767,0.0771,0.0781,0.0784,0.0813,0.0842,0.0907,0.0929
40,Serbia,0.0508,0.0532,0.0539,0.0542,0.0541,0.0551,0.0564,0.0563,0.0575,0.0591,0.0589,0.0617,0.0686,0.0755,0.0783
41,Türkiye,0.0845,0.0773,0.0727,0.0688,0.0684,0.0841,0.0805,0.066,0.0672,0.0637,0.0748,0.0833,0.0759,0.0501,0.0434
42,Ukraine,0.0328,0.0318,0.0342,0.0342,0.0369,0.0406,0.0388,0.033,0.0404,:,:,:,:,:,:
43,Kosovo*,0.0546,0.0588,0.0569,0.0579,0.0537,0.0528,0.0525,0.0525,0.0522,0.0535,0.0555,0.0583,0.0603,0.0662,0.065
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Special value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,:,not available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Data extracted on 07/03/2025 23:52:31 from [ES...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,Dataset:,Electricity prices for household consumers - b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,Last updated:,19/12/2024 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Time frequency,NaN,"Half-yearly, semesterly",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Products,NaN,Electrical energy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Energy consumption,NaN,Consumption from 2 500 kWh to 4 999 kWh - band DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Unit of measure,NaN,Kilowatt-hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Taxes,NaN,Excluding taxes and levies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Currency,NaN,Euro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Drops rows that aren't required
electricity_data = electricity_data.drop([0, 1, 2, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

# Renames the Area column to Country
electricity_data = electricity_data.rename(columns={"Area": "Country"})

In [6]:
electricity_data

,Country,2017-S1,2017-S2,2018-S1,2018-S2,2019-S1,2019-S2,2020-S1,2020-S2,2021-S1,2021-S2,2022-S1,2022-S2,2023-S1,2023-S2,2024-S1
3,Belgium,0.1929,0.179,0.1872,0.1976,0.1948,0.1954,0.1872,0.1798,0.1767,0.2015,0.2622,0.3791,0.3592,0.2793,0.2405
4,Bulgaria,0.0796,0.0819,0.0816,0.0838,0.0831,0.0798,0.0831,0.0818,0.0853,0.0909,0.0911,0.0956,0.0948,0.0993,0.0989
5,Czechia,0.1176,0.1218,0.1286,0.1299,0.1238,0.1255,0.1321,0.1283,0.1284,0.1498,0.1879,0.2077,0.2624,0.2582,0.2574
6,Denmark,0.094,0.0922,0.1011,0.1116,0.1084,0.1042,0.0951,0.0908,0.104,0.1485,0.2371,0.3636,0.2976,0.1846,0.1883
7,Germany,0.1389,0.1383,0.1379,0.1378,0.1473,0.1321,0.1430,0.1451,0.1562,0.1596,0.1899,0.2333,0.2973,0.2882,0.2806
8,Estonia,0.0926,0.095,0.0989,0.1048,0.0982,0.1027,0.0882,0.0953,0.098,0.1493,0.159,0.2085,0.1666,0.1826,0.1769
9,Ireland,0.1846,0.1865,0.1846,0.2006,0.2027,0.2130,0.2037,0.2179,0.2069,0.242,0.2693,0.3823,0.4514,0.459,0.3856
10,Greece,0.1139,0.109,0.1132,0.1125,0.1141,0.1189,0.1285,0.1278,0.1305,0.1588,0.295,0.4556,0.1876,0.1905,0.1827
11,Spain,0.1805,0.1712,0.1873,0.1947,0.1326,0.1287,0.1178,0.126,0.1358,0.1878,0.2579,0.2966,0.2165,0.2068,0.1841
12,France,0.1089,0.1132,0.1134,0.1168,0.1148,0.1260,0.1242,0.1292,0.1289,0.1356,0.1566,0.1723,0.1893,0.2161,0.2187
13,Croatia,0.1011,0.1012,0.102,0.1028,0.1028,0.1030,0.1012,0.1017,0.1003,0.1022,0.106,0.117,0.117,0.1171,0.1167
14,Italy,0.1322,0.1326,0.1285,0.1416,0.1432,0.1427,0.1382,0.1331,0.1432,0.176,0.2671,0.3192,0.323,0.2565,0.2451
15,Cyprus,0.1454,0.142,0.1445,0.1745,0.1545,0.1576,0.1497,0.1184,0.1276,0.1451,0.1693,0.2551,0.2312,0.2099,0.2106
16,Latvia,0.1043,0.1039,0.1035,0.1041,0.1136,0.1144,0.0996,0.1005,0.1024,0.1402,0.1779,0.2448,0.2521,0.2497,0.2261
17,Lithuania,0.0783,0.0777,0.0771,0.0771,0.0947,0.0947,0.1111,0.0972,0.1003,0.1122,0.1205,0.2007,0.2407,0.1919,0.1914
18,Luxembourg,0.1167,0.117,0.1283,0.1302,0.1326,0.1325,0.1465,0.1465,0.1467,0.1468,0.1673,0.1696,0.3012,0.2875,0.3024
19,Hungary,0.0886,0.0893,0.0885,0.0880,0.0882,0.0864,0.0812,0.0794,0.0795,0.079,0.0746,0.0853,0.0911,0.0891,0.0861
20,Malta,0.125,0.1221,0.1209,0.1230,0.1214,0.1227,0.1208,0.1224,0.1209,0.124,0.1221,0.1208,0.1186,0.1203,0.1181
21,Netherlands,0.1146,0.1152,0.1187,0.1212,0.1357,0.1359,0.1379,0.1365,0.1351,0.1493,0.2187,0.3197,0.4436,0.2659,0.2899
22,Austria,0.1221,0.1218,0.1232,0.1265,0.1316,0.1349,0.1358,0.1384,0.1394,0.1448,0.1579,0.209,0.2691,0.299,0.2946
23,Poland,0.096,0.095,0.0906,0.0889,0.0898,0.0867,0.0926,0.0953,0.0921,0.0882,0.0912,0.1003,0.0918,0.1164,0.1065
24,Portugal,0.1106,0.108,0.1007,0.1028,0.1181,0.1204,0.1139,0.1138,0.1131,0.1164,0.1688,0.1972,0.2983,0.2012,0.1823
25,Romania,0.0871,0.0945,0.099,0.0964,0.0983,0.1025,0.1045,0.104,0.1115,0.1167,0.1779,0.2683,0.1435,0.1441,0.1392
26,Slovenia,0.1104,0.1105,0.1108,0.1125,0.1125,0.1146,0.1063,0.118,0.1153,0.1185,0.1023,0.1533,0.1614,0.1614,0.1684
27,Slovakia,0.0832,0.0838,0.0942,0.0849,0.0962,0.0969,0.1074,0.1106,0.1057,0.102,0.1242,0.1315,0.1322,0.123,0.125
28,Finland,0.1049,0.1064,0.1074,0.1144,0.1173,0.1201,0.1178,0.1205,0.12,0.1259,0.1335,0.1806,0.1934,0.1712,0.1763
29,Sweden,0.1257,0.1305,0.1202,0.1320,0.1297,0.1316,0.1200,0.1271,0.134,0.1733,0.1815,0.2489,0.1784,0.1407,0.1571
30,Iceland,0.1263,0.12,0.1222,0.1152,0.1131,0.1132,0.1061,0.0988,0.107,0.1095,0.1205,0.122,0.1208,0.1274,0.1345
31,Liechtenstein,0.1456,0.1367,0.1651,0.1690,0.1710,0.1765,0.1823,0.1791,0.1786,0.1829,0.1898,0.1999,0.3888,0.3174,0.2811
32,Norway,0.1163,0.1137,0.1254,0.1382,0.1360,0.1264,0.0954,0.0927,0.1326,0.1752,0.2005,0.2751,0.1683,0.1521,0.1579
33,United Kingdom,0.1344,0.1344,0.1347,0.1401,0.1450,0.1512,0.1532,:,:,:,:,:,:,:,:
34,Bosnia and Herzegovina,0.072,0.0724,0.0722,0.0729,0.0729,0.0728,0.0721,0.0746,0.0721,0.0714,0.0733,0.0738,0.0742,0.0717,0.0724
35,Montenegro,0.0804,0.0806,0.0828,0.0829,0.0834,0.0847,0.0811,0.0821,0.0807,0.0803,0.0792,0.0809,0.0845,0.0846,0.0894
36,Moldova,0.0977,0.1013,0.102,0.0960,0.0936,0.1019,0.1068,0.0993,0.0851,0.0888,0.1047,0.1976,0.1795,0.1469,0.1359
37,North Macedonia,0.0695,0.0687,0.0662,0.0667,0.0664,0.0669,0.0662,0.0706,0.0713,0.08,0.0895,0.0981,0.0957,0.0982,0.0943
38,Georgia,:,:,0.058,0.0628,0.0686,0.0524,0.0562,0.0482,0.0535,0.0559,:,0.0716,0.0718,0.0733,0.0602
39,Albania,0.0703,0.0713,:,0.0759,0.0767,0.0778,0.0768,0.0767,0.0771,0.0781,0.0784,0.0813,0.0842,0.0907,0.0929
40,Serbia,0.0508,0.0532,0.0539,0.0542,0.0541,0.0551,0.0564,0.0563,0.0575,0.0591,0.0589,0.0617,0.0686,0.0755,0.0783
41,Türkiye,0.0845,0.0773,0.0727,0.0688,0.0684,0.0841,0.0805,0.066,0.0672,0.0637,0.0748,0.0833,0.0759,0.0501,0.0434
42,Ukraine,0.0328,0.0318,0.0342,0.0342,0.0369,0.0406,0.0388,0.033,0.0404,:,:,:,:,:,:

In [7]:
# Melts the data from wide to long data
# https://www.youtube.com/watch?v=F_N6oa1bksE&ab_channel=SelvaPrabhakaran%28ML%2B%
electricity_data = pd.melt(electricity_data, id_vars=['Country'], value_vars=[
        '2017-S1','2018-S1','2019-S1','2017-S1',
        '2020-S1','2021-S1','2022-S1','2023-S1','2024-S1',
        '2017-S2','2018-S2','2019-S2','2020-S2',
        '2021-S2','2022-S2','2023-S2'], var_name="Dates", value_name="Price")

electricity_data

                    Country    Dates   Price
0                   Belgium  2017-S1  0.1929
1                  Bulgaria  2017-S1  0.0796
2                   Czechia  2017-S1  0.1176
3                   Denmark  2017-S1   0.094
4                   Germany  2017-S1  0.1389
5                   Estonia  2017-S1  0.0926
6                   Ireland  2017-S1  0.1846
7                    Greece  2017-S1  0.1139
8                     Spain  2017-S1  0.1805
9                    France  2017-S1  0.1089
10                  Croatia  2017-S1  0.1011
11                    Italy  2017-S1  0.1322
12                   Cyprus  2017-S1  0.1454
13                   Latvia  2017-S1  0.1043
14                Lithuania  2017-S1  0.0783
15               Luxembourg  2017-S1  0.1167
16                  Hungary  2017-S1  0.0886
17                    Malta  2017-S1   0.125
18              Netherlands  2017-S1  0.1146
19                  Austria  2017-S1  0.1221
20                   Poland  2017-S1   0.096
21                 Portugal  2017-S1  0.1106
22                  Romania  2017-S1  0.0871
23                 Slovenia  2017-S1  0.1104
24                 Slovakia  2017-S1  0.0832
25                  Finland  2017-S1  0.1049
26                   Sweden  2017-S1  0.1257
27                  Iceland  2017-S1  0.1263
28            Liechtenstein  2017-S1  0.1456
29                   Norway  2017-S1  0.1163
30           United Kingdom  2017-S1  0.1344
31   Bosnia and Herzegovina  2017-S1   0.072
32               Montenegro  2017-S1  0.0804
33                  Moldova  2017-S1  0.0977
34          North Macedonia  2017-S1  0.0695
35                  Georgia  2017-S1       :
36                  Albania  2017-S1  0.0703
37                   Serbia  2017-S1  0.0508
38                  Türkiye  2017-S1  0.0845
39                  Ukraine  2017-S1  0.0328
40                  Belgium  2018-S1  0.1872
41                 Bulgaria  2018-S1  0.0816
42                  Czechia  2018-S1  0.1286
43                  Denmark  2018-S1  0.1011
44                  Germany  2018-S1  0.1379
45                  Estonia  2018-S1  0.0989
46                  Ireland  2018-S1  0.1846
47                   Greece  2018-S1  0.1132
48                    Spain  2018-S1  0.1873
49                   France  2018-S1  0.1134
50                  Croatia  2018-S1   0.102
51                    Italy  2018-S1  0.1285
52                   Cyprus  2018-S1  0.1445
53                   Latvia  2018-S1  0.1035
54                Lithuania  2018-S1  0.0771
55               Luxembourg  2018-S1  0.1283
56                  Hungary  2018-S1  0.0885
57                    Malta  2018-S1  0.1209
58              Netherlands  2018-S1  0.1187
59                  Austria  2018-S1  0.1232
60                   Poland  2018-S1  0.0906
61                 Portugal  2018-S1  0.1007
62                  Romania  2018-S1   0.099
63                 Slovenia  2018-S1  0.1108
64                 Slovakia  2018-S1  0.0942
65                  Finland  2018-S1  0.1074
66                   Sweden  2018-S1  0.1202
67                  Iceland  2018-S1  0.1222
68            Liechtenstein  2018-S1  0.1651
69                   Norway  2018-S1  0.1254
70           United Kingdom  2018-S1  0.1347
71   Bosnia and Herzegovina  2018-S1  0.0722
72               Montenegro  2018-S1  0.0828
73                  Moldova  2018-S1   0.102
74          North Macedonia  2018-S1  0.0662
75                  Georgia  2018-S1   0.058
76                  Albania  2018-S1       :
77                   Serbia  2018-S1  0.0539
78                  Türkiye  2018-S1  0.0727
79                  Ukraine  2018-S1  0.0342
80                  Belgium  2019-S1  0.1948
81                 Bulgaria  2019-S1  0.0831
82                  Czechia  2019-S1  0.1238
83                  Denmark  2019-S1  0.1084
84                  Germany  2019-S1  0.1473
85                  Estonia  2019-S1  0.0982
86                  Ireland  2019-S1  0.2027
87                   Greece  2019-S1  0.1141
88                    Spain  2019-S1  0.1326
89                   France  2019-S1  0.1148
90                  Croatia  2019-S1  0.1028
91                    Italy  2019-S1  0.1432
92                   Cyprus  2019-S1  0.1545
93                   Latvia  2019-S1  0.1136
94                Lithuania  2019-S1  0.0947
95               Luxembourg  2019-S1  0.1326
96                  Hungary  2019-S1  0.0882
97                    Malta  2019-S1  0.1214
98              Netherlands  2019-S1  0.1357
99                  Austria  2019-S1  0.1316
100                  Poland  2019-S1  0.0898
101                Portugal  2019-S1  0.1181
102                 Romania  2019-S1  0.0983
103                Slovenia  2019-S1  0.1125
104                Slovakia  2019-S1  0.0962
105                 Finland  2019-S1  0.1173
106                  Sweden  2019-S1  0.1297
107                 Iceland  2019-S1  0.1131
108           Liechtenstein  2019-S1   0.171
109                  Norway  2019-S1   0.136
110          United Kingdom  2019-S1   0.145
111  Bosnia and Herzegovina  2019-S1  0.0729
112              Montenegro  2019-S1  0.0834
113                 Moldova  2019-S1  0.0936
114         North Macedonia  2019-S1  0.0664
115                 Georgia  2019-S1  0.0686
116                 Albania  2019-S1  0.0767
117                  Serbia  2019-S1  0.0541
118                 Türkiye  2019-S1  0.0684
119                 Ukraine  2019-S1  0.0369
120                 Belgium  2020-S1  0.1872
121                Bulgaria  2020-S1  0.0831
122                 Czechia  2020-S1  0.1321
123                 Denmark  2020-S1  0.0951
124                 Germany  2020-S1   0.143
125                 Estonia  2020-S1  0.0882
126                 Ireland  2020-S1  0.2037
127                  Greece  2020-S1  0.1285
128                   Spain  2020-S1  0.1178
129                  France  2020-S1  0.1242
130                 Croatia  2020-S1  0.1012
131                   Italy  2020-S1  0.1382
132                  Cyprus  2020-S1  0.1497
133                  Latvia  2020-S1  0.0996
134               Lithuania  2020-S1  0.1111
135              Luxembourg  2020-S1  0.1465
136                 Hungary  2020-S1  0.0812
137                   Malta  2020-S1  0.1208
138             Netherlands  2020-S1  0.1379
139                 Austria  2020-S1  0.1358
140                  Poland  2020-S1  0.0926
141                Portugal  2020-S1  0.1139
142                 Romania  2020-S1  0.1045
143                Slovenia  2020-S1  0.1063
144                Slovakia  2020-S1  0.1074
145                 Finland  2020-S1  0.1178
146                  Sweden  2020-S1    0.12
147                 Iceland  2020-S1  0.1061
148           Liechtenstein  2020-S1  0.1823
149                  Norway  2020-S1  0.0954
150          United Kingdom  2020-S1  0.1532
151  Bosnia and Herzegovina  2020-S1  0.0721
152              Montenegro  2020-S1  0.0811
153                 Moldova  2020-S1  0.1068
154         North Macedonia  2020-S1  0.0662
155                 Georgia  2020-S1  0.0562
156                 Albania  2020-S1  0.0768
157                  Serbia  2020-S1  0.0564
158                 Türkiye  2020-S1  0.0805
159                 Ukraine  2020-S1  0.0388
160                 Belgium  2021-S1  0.1767
161                Bulgaria  2021-S1  0.0853
162                 Czechia  2021-S1  0.1284
163                 Denmark  2021-S1   0.104
164                 Germany  2021-S1  0.1562
165                 Estonia  2021-S1   0.098
166                 Ireland  2021-S1  0.2069
167                  Greece  2021-S1  0.1305
168                   Spain  2021-S1  0.1358
169                  France  2021-S1  0.1289
170                 Croatia  2021-S1  0.1003
171                   Italy  2021-S1  0.1432
172                  Cyprus  2021-S1  0.1276
173                  Latvia  2021-S1  0.1024
174               Lithuania  2021-S1  0.1003
175              Luxembourg  2021-S1  0.1467
176                 Hungary  2021-S1  0.0795
177                   Malta  2021-S1  0.1209
178             Netherlands  2021-S1  0.1351
179                 Austria  2021-S1  0.1394
180                  Poland  2021-S1  0.0921
181                Portugal  2021-S1  0.1131
182                 Romania  2021-S1  0.1115
183                Slovenia  2021-S1  0.1153
184                Slovakia  2021-S1  0.1057
185                 Finland  2021-S1    0.12
186                  Sweden  2021-S1   0.134
187                 Iceland  2021-S1   0.107
188           Liechtenstein  2021-S1  0.1786
189                  Norway  2021-S1  0.1326
190          United Kingdom  2021-S1       :
191  Bosnia and Herzegovina  2021-S1  0.0721
192              Montenegro  2021-S1  0.0807
193                 Moldova  2021-S1  0.0851
194         North Macedonia  2021-S1  0.0713
195                 Georgia  2021-S1  0.0535
196                 Albania  2021-S1  0.0771
197                  Serbia  2021-S1  0.0575
198                 Türkiye  2021-S1  0.0672
199                 Ukraine  2021-S1  0.0404
200                 Belgium  2022-S1  0.2622
201                Bulgaria  2022-S1  0.0911
202                 Czechia  2022-S1  0.1879
203                 Denmark  2022-S1  0.2371
204                 Germany  2022-S1  0.1899
205                 Estonia  2022-S1   0.159
206                 Ireland  2022-S1  0.2693
207                  Greece  2022-S1   0.295
208                   Spain  2022-S1  0.2579
209                  France  2022-S1  0.1566
210                 Croatia  2022-S1   0.106
211                   Italy  2022-S1  0.2671
212                  Cyprus  2022-S1  0.1693
213                  Latvia  2022-S1  0.1779
214               Lithuania  2022-S1  0.1205
215              Luxembourg  2022-S1  0.1673
216                 Hungary  2022-S1  0.0746
217                   Malta  2022-S1  0.1221
218             Netherlands  2022-S1  0.2187
219                 Austria  2022-S1  0.1579
220                  Poland  2022-S1  0.0912
221                Portugal  2022-S1  0.1688
222                 Romania  2022-S1  0.1779
223                Slovenia  2022-S1  0.1023
224                Slovakia  2022-S1  0.1242
225                 Finland  2022-S1  0.1335
226                  Sweden  2022-S1  0.1815
227                 Iceland  2022-S1  0.1205
228           Liechtenstein  2022-S1  0.1898
229                  Norway  2022-S1  0.2005
230          United Kingdom  2022-S1       :
231  Bosnia and Herzegovina  2022-S1  0.0733
232              Montenegro  2022-S1  0.0792
233                 Moldova  2022-S1  0.1047
234         North Macedonia  2022-S1  0.0895
235                 Georgia  2022-S1       :
236                 Albania  2022-S1  0.0784
237                  Serbia  2022-S1  0.0589
238                 Türkiye  2022-S1  0.0748
239                 Ukraine  2022-S1       :
240                 Belgium  2023-S1  0.3592
241                Bulgaria  2023-S1  0.0948
242                 Czechia  2023-S1  0.2624
243                 Denmark  2023-S1  0.2976
244                 Germany  2023-S1  0.2973
245                 Estonia  2023-S1  0.1666
246                 Ireland  2023-S1  0.4514
247                  Greece  2023-S1  0.1876
248                   Spain  2023-S1  0.2165
249                  France  2023-S1  0.1893
250                 Croatia  2023-S1   0.117
251                   Italy  2023-S1   0.323
252                  Cyprus  2023-S1  0.2312
253                  Latvia  2023-S1  0.2521
254               Lithuania  2023-S1  0.2407
255              Luxembourg  2023-S1  0.3012
256                 Hungary  2023-S1  0.0911
257                   Malta  2023-S1  0.1186
258             Netherlands  2023-S1  0.4436
259                 Austria  2023-S1  0.2691
260                  Poland  2023-S1  0.0918
261                Portugal  2023-S1  0.2983
262                 Romania  2023-S1  0.1435
263                Slovenia  2023-S1  0.1614
264                Slovakia  2023-S1  0.1322
265                 Finland  2023-S1  0.1934
266                  Sweden  2023-S1  0.1784
267                 Iceland  2023-S1  0.1208
268           Liechtenstein  2023-S1  0.3888
269                  Norway  2023-S1  0.1683
270          United Kingdom  2023-S1       :
271  Bosnia and Herzegovina  2023-S1  0.0742
272              Montenegro  2023-S1  0.0845
273                 Moldova  2023-S1  0.1795
274         North Macedonia  2023-S1  0.0957
275                 Georgia  2023-S1  0.0718
276                 Albania  2023-S1  0.0842
277                  Serbia  2023-S1  0.0686
278                 Türkiye  2023-S1  0.0759
279                 Ukraine  2023-S1       :
280                 Belgium  2024-S1  0.2405
281                Bulgaria  2024-S1  0.0989
282                 Czechia  2024-S1  0.2574
283                 Denmark  2024-S1  0.1883
284                 Germany  2024-S1  0.2806
285                 Estonia  2024-S1  0.1769
286                 Ireland  2024-S1  0.3856
287                  Greece  2024-S1  0.1827
288                   Spain  2024-S1  0.1841
289                  France  2024-S1  0.2187
290                 Croatia  2024-S1  0.1167
291                   Italy  2024-S1  0.2451
292                  Cyprus  2024-S1  0.2106
293                  Latvia  2024-S1  0.2261
294               Lithuania  2024-S1  0.1914
295              Luxembourg  2024-S1  0.3024
296                 Hungary  2024-S1  0.0861
297                   Malta  2024-S1  0.1181
298             Netherlands  2024-S1  0.2899
299                 Austria  2024-S1  0.2946
300                  Poland  2024-S1  0.1065
301                Portugal  2024-S1  0.1823
302                 Romania  2024-S1  0.1392
303                Slovenia  2024-S1  0.1684
304                Slovakia  2024-S1   0.125
305                 Finland  2024-S1  0.1763
306                  Sweden  2024-S1  0.1571
307                 Iceland  2024-S1  0.1345
308           Liechtenstein  2024-S1  0.2811
309                  Norway  2024-S1  0.1579
310          United Kingdom  2024-S1       :
311  Bosnia and Herzegovina  2024-S1  0.0724
312              Montenegro  2024-S1  0.0894
313                 Moldova  2024-S1  0.1359
314         North Macedonia  2024-S1  0.0943
315                 Georgia  2024-S1  0.0602
316                 Albania  2024-S1  0.0929
317                  Serbia  2024-S1  0.0783
318                 Türkiye  2024-S1  0.0434
319                 Ukraine  2024-S1       :
320                 Belgium  2017-S2   0.179
321                Bulgaria  2017-S2  0.0819
322                 Czechia  2017-S2  0.1218
323                 Denmark  2017-S2  0.0922
324                 Germany  2017-S2  0.1383
325                 Estonia  2017-S2   0.095
326                 Ireland  2017-S2  0.1865
327                  Greece  2017-S2   0.109
328                   Spain  2017-S2  0.1712
329                  France  2017-S2  0.1132
330                 Croatia  2017-S2  0.1012
331                   Italy  2017-S2  0.1326
332                  Cyprus  2017-S2   0.142
333                  Latvia  2017-S2  0.1039
334               Lithuania  2017-S2  0.0777
335              Luxembourg  2017-S2   0.117
336                 Hungary  2017-S2  0.0893
337                   Malta  2017-S2  0.1221
338             Netherlands  2017-S2  0.1152
339                 Austria  2017-S2  0.1218
340                  Poland  2017-S2   0.095
341                Portugal  2017-S2   0.108
342                 Romania  2017-S2  0.0945
343                Slovenia  2017-S2  0.1105
344                Slovakia  2017-S2  0.0838
345                 Finland  2017-S2  0.1064
346                  Sweden  2017-S2  0.1305
347                 Iceland  2017-S2    0.12
348           Liechtenstein  2017-S2  0.1367
349                  Norway  2017-S2  0.1137
350          United Kingdom  2017-S2  0.1344
351  Bosnia and Herzegovina  2017-S2  0.0724
352              Montenegro  2017-S2  0.0806
353                 Moldova  2017-S2  0.1013
354         North Macedonia  2017-S2  0.0687
355                 Georgia  2017-S2       :
356                 Albania  2017-S2  0.0713
357                  Serbia  2017-S2  0.0532
358                 Türkiye  2017-S2  0.0773
359                 Ukraine  2017-S2  0.0318
360                 Belgium  2018-S2  0.1976
361                Bulgaria  2018-S2  0.0838
362                 Czechia  2018-S2  0.1299
363                 Denmark  2018-S2  0.1116
364                 Germany  2018-S2  0.1378
365                 Estonia  2018-S2  0.1048
366                 Ireland  2018-S2  0.2006
367                  Greece  2018-S2  0.1125
368                   Spain  2018-S2  0.1947
369                  France  2018-S2  0.1168
370                 Croatia  2018-S2  0.1028
371                   Italy  2018-S2  0.1416
372                  Cyprus  2018-S2  0.1745
373                  Latvia  2018-S2  0.1041
374               Lithuania  2018-S2  0.0771
375              Luxembourg  2018-S2  0.1302
376                 Hungary  2018-S2   0.088
377                   Malta  2018-S2   0.123
378             Netherlands  2018-S2  0.1212
379                 Austria  2018-S2  0.1265
380                  Poland  2018-S2  0.0889
381                Portugal  2018-S2  0.1028
382                 Romania  2018-S2  0.0964
383                Slovenia  2018-S2  0.1125
384                Slovakia  2018-S2  0.0849
385                 Finland  2018-S2  0.1144
386                  Sweden  2018-S2   0.132
387                 Iceland  2018-S2  0.1152
388           Liechtenstein  2018-S2   0.169
389                  Norway  2018-S2  0.1382
390          United Kingdom  2018-S2  0.1401
391  Bosnia and Herzegovina  2018-S2  0.0729
392              Montenegro  2018-S2  0.0829
393                 Moldova  2018-S2   0.096
394         North Macedonia  2018-S2  0.0667
395                 Georgia  2018-S2  0.0628
396                 Albania  2018-S2  0.0759
397                  Serbia  2018-S2  0.0542
398                 Türkiye  2018-S2  0.0688
399                 Ukraine  2018-S2  0.0342
400                 Belgium  2019-S2  0.1954
401                Bulgaria  2019-S2  0.0798
402                 Czechia  2019-S2  0.1255
403                 Denmark  2019-S2  0.1042
404                 Germany  2019-S2  0.1321
405                 Estonia  2019-S2  0.1027
406                 Ireland  2019-S2   0.213
407                  Greece  2019-S2  0.1189
408                   Spain  2019-S2  0.1287
409                  France  2019-S2   0.126
410                 Croatia  2019-S2   0.103
411                   Italy  2019-S2  0.1427
412                  Cyprus  2019-S2  0.1576
413                  Latvia  2019-S2  0.1144
414               Lithuania  2019-S2  0.0947
415              Luxembourg  2019-S2  0.1325
416                 Hungary  2019-S2  0.0864
417                   Malta  2019-S2  0.1227
418             Netherlands  2019-S2  0.1359
419                 Austria  2019-S2  0.1349
420                  Poland  2019-S2  0.0867
421                Portugal  2019-S2  0.1204
422                 Romania  2019-S2  0.1025
423                Slovenia  2019-S2  0.1146
424                Slovakia  2019-S2  0.0969
425                 Finland  2019-S2  0.1201
426                  Sweden  2019-S2  0.1316
427                 Iceland  2019-S2  0.1132
428           Liechtenstein  2019-S2  0.1765
429                  Norway  2019-S2  0.1264
430          United Kingdom  2019-S2  0.1512
431  Bosnia and Herzegovina  2019-S2  0.0728
432              Montenegro  2019-S2  0.0847
433                 Moldova  2019-S2  0.1019
434         North Macedonia  2019-S2  0.0669
435                 Georgia  2019-S2  0.0524
436                 Albania  2019-S2  0.0778
437                  Serbia  2019-S2  0.0551
438                 Türkiye  2019-S2  0.0841
439                 Ukraine  2019-S2  0.0406
440                 Belgium  2020-S2  0.1798
441                Bulgaria  2020-S2  0.0818
442                 Czechia  2020-S2  0.1283

In [8]:
# adds a year column from the values from Dates first 4 chars
electricity_data["Year"] = electricity_data["Dates"].str[:4].astype(int)
electricity_data = electricity_data.drop(columns="Dates")

In [9]:
electricity_data

                    Country   Price  Year
0                   Belgium  0.1929  2017
1                  Bulgaria  0.0796  2017
2                   Czechia  0.1176  2017
3                   Denmark   0.094  2017
4                   Germany  0.1389  2017
5                   Estonia  0.0926  2017
6                   Ireland  0.1846  2017
7                    Greece  0.1139  2017
8                     Spain  0.1805  2017
9                    France  0.1089  2017
10                  Croatia  0.1011  2017
11                    Italy  0.1322  2017
12                   Cyprus  0.1454  2017
13                   Latvia  0.1043  2017
14                Lithuania  0.0783  2017
15               Luxembourg  0.1167  2017
16                  Hungary  0.0886  2017
17                    Malta   0.125  2017
18              Netherlands  0.1146  2017
19                  Austria  0.1221  2017
20                   Poland   0.096  2017
21                 Portugal  0.1106  2017
22                  Romania  0.0871  2017
23                 Slovenia  0.1104  2017
24                 Slovakia  0.0832  2017
25                  Finland  0.1049  2017
26                   Sweden  0.1257  2017
27                  Iceland  0.1263  2017
28            Liechtenstein  0.1456  2017
29                   Norway  0.1163  2017
30           United Kingdom  0.1344  2017
31   Bosnia and Herzegovina   0.072  2017
32               Montenegro  0.0804  2017
33                  Moldova  0.0977  2017
34          North Macedonia  0.0695  2017
35                  Georgia       :  2017
36                  Albania  0.0703  2017
37                   Serbia  0.0508  2017
38                  Türkiye  0.0845  2017
39                  Ukraine  0.0328  2017
40                  Belgium  0.1872  2018
41                 Bulgaria  0.0816  2018
42                  Czechia  0.1286  2018
43                  Denmark  0.1011  2018
44                  Germany  0.1379  2018
45                  Estonia  0.0989  2018
46                  Ireland  0.1846  2018
47                   Greece  0.1132  2018
48                    Spain  0.1873  2018
49                   France  0.1134  2018
50                  Croatia   0.102  2018
51                    Italy  0.1285  2018
52                   Cyprus  0.1445  2018
53                   Latvia  0.1035  2018
54                Lithuania  0.0771  2018
55               Luxembourg  0.1283  2018
56                  Hungary  0.0885  2018
57                    Malta  0.1209  2018
58              Netherlands  0.1187  2018
59                  Austria  0.1232  2018
60                   Poland  0.0906  2018
61                 Portugal  0.1007  2018
62                  Romania   0.099  2018
63                 Slovenia  0.1108  2018
64                 Slovakia  0.0942  2018
65                  Finland  0.1074  2018
66                   Sweden  0.1202  2018
67                  Iceland  0.1222  2018
68            Liechtenstein  0.1651  2018
69                   Norway  0.1254  2018
70           United Kingdom  0.1347  2018
71   Bosnia and Herzegovina  0.0722  2018
72               Montenegro  0.0828  2018
73                  Moldova   0.102  2018
74          North Macedonia  0.0662  2018
75                  Georgia   0.058  2018
76                  Albania       :  2018
77                   Serbia  0.0539  2018
78                  Türkiye  0.0727  2018
79                  Ukraine  0.0342  2018
80                  Belgium  0.1948  2019
81                 Bulgaria  0.0831  2019
82                  Czechia  0.1238  2019
83                  Denmark  0.1084  2019
84                  Germany  0.1473  2019
85                  Estonia  0.0982  2019
86                  Ireland  0.2027  2019
87                   Greece  0.1141  2019
88                    Spain  0.1326  2019
89                   France  0.1148  2019
90                  Croatia  0.1028  2019
91                    Italy  0.1432  2019
92                   Cyprus  0.1545  2019
93                   Latvia  0.1136  2019
94                Lithuania  0.0947  2019
95               Luxembourg  0.1326  2019
96                  Hungary  0.0882  2019
97                    Malta  0.1214  2019
98              Netherlands  0.1357  2019
99                  Austria  0.1316  2019
100                  Poland  0.0898  2019
101                Portugal  0.1181  2019
102                 Romania  0.0983  2019
103                Slovenia  0.1125  2019
104                Slovakia  0.0962  2019
105                 Finland  0.1173  2019
106                  Sweden  0.1297  2019
107                 Iceland  0.1131  2019
108           Liechtenstein   0.171  2019
109                  Norway   0.136  2019
110          United Kingdom   0.145  2019
111  Bosnia and Herzegovina  0.0729  2019
112              Montenegro  0.0834  2019
113                 Moldova  0.0936  2019
114         North Macedonia  0.0664  2019
115                 Georgia  0.0686  2019
116                 Albania  0.0767  2019
117                  Serbia  0.0541  2019
118                 Türkiye  0.0684  2019
119                 Ukraine  0.0369  2019
120                 Belgium  0.1872  2020
121                Bulgaria  0.0831  2020
122                 Czechia  0.1321  2020
123                 Denmark  0.0951  2020
124                 Germany   0.143  2020
125                 Estonia  0.0882  2020
126                 Ireland  0.2037  2020
127                  Greece  0.1285  2020
128                   Spain  0.1178  2020
129                  France  0.1242  2020
130                 Croatia  0.1012  2020
131                   Italy  0.1382  2020
132                  Cyprus  0.1497  2020
133                  Latvia  0.0996  2020
134               Lithuania  0.1111  2020
135              Luxembourg  0.1465  2020
136                 Hungary  0.0812  2020
137                   Malta  0.1208  2020
138             Netherlands  0.1379  2020
139                 Austria  0.1358  2020
140                  Poland  0.0926  2020
141                Portugal  0.1139  2020
142                 Romania  0.1045  2020
143                Slovenia  0.1063  2020
144                Slovakia  0.1074  2020
145                 Finland  0.1178  2020
146                  Sweden    0.12  2020
147                 Iceland  0.1061  2020
148           Liechtenstein  0.1823  2020
149                  Norway  0.0954  2020
150          United Kingdom  0.1532  2020
151  Bosnia and Herzegovina  0.0721  2020
152              Montenegro  0.0811  2020
153                 Moldova  0.1068  2020
154         North Macedonia  0.0662  2020
155                 Georgia  0.0562  2020
156                 Albania  0.0768  2020
157                  Serbia  0.0564  2020
158                 Türkiye  0.0805  2020
159                 Ukraine  0.0388  2020
160                 Belgium  0.1767  2021
161                Bulgaria  0.0853  2021
162                 Czechia  0.1284  2021
163                 Denmark   0.104  2021
164                 Germany  0.1562  2021
165                 Estonia   0.098  2021
166                 Ireland  0.2069  2021
167                  Greece  0.1305  2021
168                   Spain  0.1358  2021
169                  France  0.1289  2021
170                 Croatia  0.1003  2021
171                   Italy  0.1432  2021
172                  Cyprus  0.1276  2021
173                  Latvia  0.1024  2021
174               Lithuania  0.1003  2021
175              Luxembourg  0.1467  2021
176                 Hungary  0.0795  2021
177                   Malta  0.1209  2021
178             Netherlands  0.1351  2021
179                 Austria  0.1394  2021
180                  Poland  0.0921  2021
181                Portugal  0.1131  2021
182                 Romania  0.1115  2021
183                Slovenia  0.1153  2021
184                Slovakia  0.1057  2021
185                 Finland    0.12  2021
186                  Sweden   0.134  2021
187                 Iceland   0.107  2021
188           Liechtenstein  0.1786  2021
189                  Norway  0.1326  2021
190          United Kingdom       :  2021
191  Bosnia and Herzegovina  0.0721  2021
192              Montenegro  0.0807  2021
193                 Moldova  0.0851  2021
194         North Macedonia  0.0713  2021
195                 Georgia  0.0535  2021
196                 Albania  0.0771  2021
197                  Serbia  0.0575  2021
198                 Türkiye  0.0672  2021
199                 Ukraine  0.0404  2021
200                 Belgium  0.2622  2022
201                Bulgaria  0.0911  2022
202                 Czechia  0.1879  2022
203                 Denmark  0.2371  2022
204                 Germany  0.1899  2022
205                 Estonia   0.159  2022
206                 Ireland  0.2693  2022
207                  Greece   0.295  2022
208                   Spain  0.2579  2022
209                  France  0.1566  2022
210                 Croatia   0.106  2022
211                   Italy  0.2671  2022
212                  Cyprus  0.1693  2022
213                  Latvia  0.1779  2022
214               Lithuania  0.1205  2022
215              Luxembourg  0.1673  2022
216                 Hungary  0.0746  2022
217                   Malta  0.1221  2022
218             Netherlands  0.2187  2022
219                 Austria  0.1579  2022
220                  Poland  0.0912  2022
221                Portugal  0.1688  2022
222                 Romania  0.1779  2022
223                Slovenia  0.1023  2022
224                Slovakia  0.1242  2022
225                 Finland  0.1335  2022
226                  Sweden  0.1815  2022
227                 Iceland  0.1205  2022
228           Liechtenstein  0.1898  2022
229                  Norway  0.2005  2022
230          United Kingdom       :  2022
231  Bosnia and Herzegovina  0.0733  2022
232              Montenegro  0.0792  2022
233                 Moldova  0.1047  2022
234         North Macedonia  0.0895  2022
235                 Georgia       :  2022
236                 Albania  0.0784  2022
237                  Serbia  0.0589  2022
238                 Türkiye  0.0748  2022
239                 Ukraine       :  2022
240                 Belgium  0.3592  2023
241                Bulgaria  0.0948  2023
242                 Czechia  0.2624  2023
243                 Denmark  0.2976  2023
244                 Germany  0.2973  2023
245                 Estonia  0.1666  2023
246                 Ireland  0.4514  2023
247                  Greece  0.1876  2023
248                   Spain  0.2165  2023
249                  France  0.1893  2023
250                 Croatia   0.117  2023
251                   Italy   0.323  2023
252                  Cyprus  0.2312  2023
253                  Latvia  0.2521  2023
254               Lithuania  0.2407  2023
255              Luxembourg  0.3012  2023
256                 Hungary  0.0911  2023
257                   Malta  0.1186  2023
258             Netherlands  0.4436  2023
259                 Austria  0.2691  2023
260                  Poland  0.0918  2023
261                Portugal  0.2983  2023
262                 Romania  0.1435  2023
263                Slovenia  0.1614  2023
264                Slovakia  0.1322  2023
265                 Finland  0.1934  2023
266                  Sweden  0.1784  2023
267                 Iceland  0.1208  2023
268           Liechtenstein  0.3888  2023
269                  Norway  0.1683  2023
270          United Kingdom       :  2023
271  Bosnia and Herzegovina  0.0742  2023
272              Montenegro  0.0845  2023
273                 Moldova  0.1795  2023
274         North Macedonia  0.0957  2023
275                 Georgia  0.0718  2023
276                 Albania  0.0842  2023
277                  Serbia  0.0686  2023
278                 Türkiye  0.0759  2023
279                 Ukraine       :  2023
280                 Belgium  0.2405  2024
281                Bulgaria  0.0989  2024
282                 Czechia  0.2574  2024
283                 Denmark  0.1883  2024
284                 Germany  0.2806  2024
285                 Estonia  0.1769  2024
286                 Ireland  0.3856  2024
287                  Greece  0.1827  2024
288                   Spain  0.1841  2024
289                  France  0.2187  2024
290                 Croatia  0.1167  2024
291                   Italy  0.2451  2024
292                  Cyprus  0.2106  2024
293                  Latvia  0.2261  2024
294               Lithuania  0.1914  2024
295              Luxembourg  0.3024  2024
296                 Hungary  0.0861  2024
297                   Malta  0.1181  2024
298             Netherlands  0.2899  2024
299                 Austria  0.2946  2024
300                  Poland  0.1065  2024
301                Portugal  0.1823  2024
302                 Romania  0.1392  2024
303                Slovenia  0.1684  2024
304                Slovakia   0.125  2024
305                 Finland  0.1763  2024
306                  Sweden  0.1571  2024
307                 Iceland  0.1345  2024
308           Liechtenstein  0.2811  2024
309                  Norway  0.1579  2024
310          United Kingdom       :  2024
311  Bosnia and Herzegovina  0.0724  2024
312              Montenegro  0.0894  2024
313                 Moldova  0.1359  2024
314         North Macedonia  0.0943  2024
315                 Georgia  0.0602  2024
316                 Albania  0.0929  2024
317                  Serbia  0.0783  2024
318                 Türkiye  0.0434  2024
319                 Ukraine       :  2024
320                 Belgium   0.179  2017
321                Bulgaria  0.0819  2017
322                 Czechia  0.1218  2017
323                 Denmark  0.0922  2017
324                 Germany  0.1383  2017
325                 Estonia   0.095  2017
326                 Ireland  0.1865  2017
327                  Greece   0.109  2017
328                   Spain  0.1712  2017
329                  France  0.1132  2017
330                 Croatia  0.1012  2017
331                   Italy  0.1326  2017
332                  Cyprus   0.142  2017
333                  Latvia  0.1039  2017
334               Lithuania  0.0777  2017
335              Luxembourg   0.117  2017
336                 Hungary  0.0893  2017
337                   Malta  0.1221  2017
338             Netherlands  0.1152  2017
339                 Austria  0.1218  2017
340                  Poland   0.095  2017
341                Portugal   0.108  2017
342                 Romania  0.0945  2017
343                Slovenia  0.1105  2017
344                Slovakia  0.0838  2017
345                 Finland  0.1064  2017
346                  Sweden  0.1305  2017
347                 Iceland    0.12  2017
348           Liechtenstein  0.1367  2017
349                  Norway  0.1137  2017
350          United Kingdom  0.1344  2017
351  Bosnia and Herzegovina  0.0724  2017
352              Montenegro  0.0806  2017
353                 Moldova  0.1013  2017
354         North Macedonia  0.0687  2017
355                 Georgia       :  2017
356                 Albania  0.0713  2017
357                  Serbia  0.0532  2017
358                 Türkiye  0.0773  2017
359                 Ukraine  0.0318  2017
360                 Belgium  0.1976  2018
361                Bulgaria  0.0838  2018
362                 Czechia  0.1299  2018
363                 Denmark  0.1116  2018
364                 Germany  0.1378  2018
365                 Estonia  0.1048  2018
366                 Ireland  0.2006  2018
367                  Greece  0.1125  2018
368                   Spain  0.1947  2018
369                  France  0.1168  2018
370                 Croatia  0.1028  2018
371                   Italy  0.1416  2018
372                  Cyprus  0.1745  2018
373                  Latvia  0.1041  2018
374               Lithuania  0.0771  2018
375              Luxembourg  0.1302  2018
376                 Hungary   0.088  2018
377                   Malta   0.123  2018
378             Netherlands  0.1212  2018
379                 Austria  0.1265  2018
380                  Poland  0.0889  2018
381                Portugal  0.1028  2018
382                 Romania  0.0964  2018
383                Slovenia  0.1125  2018
384                Slovakia  0.0849  2018
385                 Finland  0.1144  2018
386                  Sweden   0.132  2018
387                 Iceland  0.1152  2018
388           Liechtenstein   0.169  2018
389                  Norway  0.1382  2018
390          United Kingdom  0.1401  2018
391  Bosnia and Herzegovina  0.0729  2018
392              Montenegro  0.0829  2018
393                 Moldova   0.096  2018
394         North Macedonia  0.0667  2018
395                 Georgia  0.0628  2018
396                 Albania  0.0759  2018
397                  Serbia  0.0542  2018
398                 Türkiye  0.0688  2018
399                 Ukraine  0.0342  2018
400                 Belgium  0.1954  2019
401                Bulgaria  0.0798  2019
402                 Czechia  0.1255  2019
403                 Denmark  0.1042  2019
404                 Germany  0.1321  2019
405                 Estonia  0.1027  2019
406                 Ireland   0.213  2019
407                  Greece  0.1189  2019
408                   Spain  0.1287  2019
409                  France   0.126  2019
410                 Croatia   0.103  2019
411                   Italy  0.1427  2019
412                  Cyprus  0.1576  2019
413                  Latvia  0.1144  2019
414               Lithuania  0.0947  2019
415              Luxembourg  0.1325  2019
416                 Hungary  0.0864  2019
417                   Malta  0.1227  2019
418             Netherlands  0.1359  2019
419                 Austria  0.1349  2019
420                  Poland  0.0867  2019
421                Portugal  0.1204  2019
422                 Romania  0.1025  2019
423                Slovenia  0.1146  2019
424                Slovakia  0.0969  2019
425                 Finland  0.1201  2019
426                  Sweden  0.1316  2019
427                 Iceland  0.1132  2019
428           Liechtenstein  0.1765  2019
429                  Norway  0.1264  2019
430          United Kingdom  0.1512  2019
431  Bosnia and Herzegovina  0.0728  2019
432              Montenegro  0.0847  2019
433                 Moldova  0.1019  2019
434         North Macedonia  0.0669  2019
435                 Georgia  0.0524  2019
436                 Albania  0.0778  2019
437                  Serbia  0.0551  2019
438                 Türkiye  0.0841  2019
439                 Ukraine  0.0406  2019
440                 Belgium  0.1798  2020
441                Bulgaria  0.0818  2020
442                 Czechia  0.1283  2020
443                 Denmark  0.0908  2020
444                 Germany  0.1451  2020
445                 Estonia  0.0953  2020
446                 Ireland  0.2179  2020
447                  Greece  0.1278  2020
448                   Spain   0.126  2020
449                  France  0.1292  2020
450                 Croatia  0.1017  2020
451                   Italy  0.1331  2020
452                  Cyprus  0.1184  2020
453                  Latvia  0.1005  2020
454               Lithuania  0.0972  2020
455              Luxembourg  0.1465  2020
456                 Hungary  0.0794  2020
457                   Malta  0.1224  2020
458             Netherlands  0.1365  2020
459                 Austria  0.1384  2020
460                  Poland  0.0953  2020
461                Portugal  0.1138  2020
462                 Romania   0.104  2020
463                Slovenia   0.118  2020
464                Slovakia  0.1106  2020
465                 Finland  0.1205  2020
466                  Sweden  0.1271  2020
467                 Iceland  0.0988  2020
468           Liechtenstein  0.1791  2020
469                  Norway  0.0927  2020
470          United Kingdom       :  2020
471  Bosnia and Herzegovina  0.0746  2020
472              Montenegro  0.0821  2020
473                 Moldova  0.0993  2020
474         North Macedonia  0.0706  2020

In [10]:
# Referenced from https://stackoverflow.com/questions/47919846/using-pycountry-to-check-for-name-common-name-official-name
import pycountry
def get_country_code(name):
    for co in list(pycountry.countries):
        if name in co.name:
            return co.alpha_3
    return None

electricity_data["countryISO"] = electricity_data["Country"].apply(get_country_code)

In [11]:
# checks for any missing values in countryISO field
missing = electricity_data['countryISO'].isna().sum()
print(f"{missing}")

0

In [12]:
electricity_data

                    Country   Price  Year countryISO
0                   Belgium  0.1929  2017        BEL
1                  Bulgaria  0.0796  2017        BGR
2                   Czechia  0.1176  2017        CZE
3                   Denmark   0.094  2017        DNK
4                   Germany  0.1389  2017        DEU
5                   Estonia  0.0926  2017        EST
6                   Ireland  0.1846  2017        IRL
7                    Greece  0.1139  2017        GRC
8                     Spain  0.1805  2017        ESP
9                    France  0.1089  2017        FRA
10                  Croatia  0.1011  2017        HRV
11                    Italy  0.1322  2017        ITA
12                   Cyprus  0.1454  2017        CYP
13                   Latvia  0.1043  2017        LVA
14                Lithuania  0.0783  2017        LTU
15               Luxembourg  0.1167  2017        LUX
16                  Hungary  0.0886  2017        HUN
17                    Malta   0.125  2017        MLT
18              Netherlands  0.1146  2017        NLD
19                  Austria  0.1221  2017        AUT
20                   Poland   0.096  2017        POL
21                 Portugal  0.1106  2017        PRT
22                  Romania  0.0871  2017        ROU
23                 Slovenia  0.1104  2017        SVN
24                 Slovakia  0.0832  2017        SVK
25                  Finland  0.1049  2017        FIN
26                   Sweden  0.1257  2017        SWE
27                  Iceland  0.1263  2017        ISL
28            Liechtenstein  0.1456  2017        LIE
29                   Norway  0.1163  2017        NOR
30           United Kingdom  0.1344  2017        GBR
31   Bosnia and Herzegovina   0.072  2017        BIH
32               Montenegro  0.0804  2017        MNE
33                  Moldova  0.0977  2017        MDA
34          North Macedonia  0.0695  2017        MKD
35                  Georgia       :  2017        GEO
36                  Albania  0.0703  2017        ALB
37                   Serbia  0.0508  2017        SRB
38                  Türkiye  0.0845  2017        TUR
39                  Ukraine  0.0328  2017        UKR
40                  Belgium  0.1872  2018        BEL
41                 Bulgaria  0.0816  2018        BGR
42                  Czechia  0.1286  2018        CZE
43                  Denmark  0.1011  2018        DNK
44                  Germany  0.1379  2018        DEU
45                  Estonia  0.0989  2018        EST
46                  Ireland  0.1846  2018        IRL
47                   Greece  0.1132  2018        GRC
48                    Spain  0.1873  2018        ESP
49                   France  0.1134  2018        FRA
50                  Croatia   0.102  2018        HRV
51                    Italy  0.1285  2018        ITA
52                   Cyprus  0.1445  2018        CYP
53                   Latvia  0.1035  2018        LVA
54                Lithuania  0.0771  2018        LTU
55               Luxembourg  0.1283  2018        LUX
56                  Hungary  0.0885  2018        HUN
57                    Malta  0.1209  2018        MLT
58              Netherlands  0.1187  2018        NLD
59                  Austria  0.1232  2018        AUT
60                   Poland  0.0906  2018        POL
61                 Portugal  0.1007  2018        PRT
62                  Romania   0.099  2018        ROU
63                 Slovenia  0.1108  2018        SVN
64                 Slovakia  0.0942  2018        SVK
65                  Finland  0.1074  2018        FIN
66                   Sweden  0.1202  2018        SWE
67                  Iceland  0.1222  2018        ISL
68            Liechtenstein  0.1651  2018        LIE
69                   Norway  0.1254  2018        NOR
70           United Kingdom  0.1347  2018        GBR
71   Bosnia and Herzegovina  0.0722  2018        BIH
72               Montenegro  0.0828  2018        MNE
73                  Moldova   0.102  2018        MDA
74          North Macedonia  0.0662  2018        MKD
75                  Georgia   0.058  2018        GEO
76                  Albania       :  2018        ALB
77                   Serbia  0.0539  2018        SRB
78                  Türkiye  0.0727  2018        TUR
79                  Ukraine  0.0342  2018        UKR
80                  Belgium  0.1948  2019        BEL
81                 Bulgaria  0.0831  2019        BGR
82                  Czechia  0.1238  2019        CZE
83                  Denmark  0.1084  2019        DNK
84                  Germany  0.1473  2019        DEU
85                  Estonia  0.0982  2019        EST
86                  Ireland  0.2027  2019        IRL
87                   Greece  0.1141  2019        GRC
88                    Spain  0.1326  2019        ESP
89                   France  0.1148  2019        FRA
90                  Croatia  0.1028  2019        HRV
91                    Italy  0.1432  2019        ITA
92                   Cyprus  0.1545  2019        CYP
93                   Latvia  0.1136  2019        LVA
94                Lithuania  0.0947  2019        LTU
95               Luxembourg  0.1326  2019        LUX
96                  Hungary  0.0882  2019        HUN
97                    Malta  0.1214  2019        MLT
98              Netherlands  0.1357  2019        NLD
99                  Austria  0.1316  2019        AUT
100                  Poland  0.0898  2019        POL
101                Portugal  0.1181  2019        PRT
102                 Romania  0.0983  2019        ROU
103                Slovenia  0.1125  2019        SVN
104                Slovakia  0.0962  2019        SVK
105                 Finland  0.1173  2019        FIN
106                  Sweden  0.1297  2019        SWE
107                 Iceland  0.1131  2019        ISL
108           Liechtenstein   0.171  2019        LIE
109                  Norway   0.136  2019        NOR
110          United Kingdom   0.145  2019        GBR
111  Bosnia and Herzegovina  0.0729  2019        BIH
112              Montenegro  0.0834  2019        MNE
113                 Moldova  0.0936  2019        MDA
114         North Macedonia  0.0664  2019        MKD
115                 Georgia  0.0686  2019        GEO
116                 Albania  0.0767  2019        ALB
117                  Serbia  0.0541  2019        SRB
118                 Türkiye  0.0684  2019        TUR
119                 Ukraine  0.0369  2019        UKR
120                 Belgium  0.1872  2020        BEL
121                Bulgaria  0.0831  2020        BGR
122                 Czechia  0.1321  2020        CZE
123                 Denmark  0.0951  2020        DNK
124                 Germany   0.143  2020        DEU
125                 Estonia  0.0882  2020        EST
126                 Ireland  0.2037  2020        IRL
127                  Greece  0.1285  2020        GRC
128                   Spain  0.1178  2020        ESP
129                  France  0.1242  2020        FRA
130                 Croatia  0.1012  2020        HRV
131                   Italy  0.1382  2020        ITA
132                  Cyprus  0.1497  2020        CYP
133                  Latvia  0.0996  2020        LVA
134               Lithuania  0.1111  2020        LTU
135              Luxembourg  0.1465  2020        LUX
136                 Hungary  0.0812  2020        HUN
137                   Malta  0.1208  2020        MLT
138             Netherlands  0.1379  2020        NLD
139                 Austria  0.1358  2020        AUT
140                  Poland  0.0926  2020        POL
141                Portugal  0.1139  2020        PRT
142                 Romania  0.1045  2020        ROU
143                Slovenia  0.1063  2020        SVN
144                Slovakia  0.1074  2020        SVK
145                 Finland  0.1178  2020        FIN
146                  Sweden    0.12  2020        SWE
147                 Iceland  0.1061  2020        ISL
148           Liechtenstein  0.1823  2020        LIE
149                  Norway  0.0954  2020        NOR
150          United Kingdom  0.1532  2020        GBR
151  Bosnia and Herzegovina  0.0721  2020        BIH
152              Montenegro  0.0811  2020        MNE
153                 Moldova  0.1068  2020        MDA
154         North Macedonia  0.0662  2020        MKD
155                 Georgia  0.0562  2020        GEO
156                 Albania  0.0768  2020        ALB
157                  Serbia  0.0564  2020        SRB
158                 Türkiye  0.0805  2020        TUR
159                 Ukraine  0.0388  2020        UKR
160                 Belgium  0.1767  2021        BEL
161                Bulgaria  0.0853  2021        BGR
162                 Czechia  0.1284  2021        CZE
163                 Denmark   0.104  2021        DNK
164                 Germany  0.1562  2021        DEU
165                 Estonia   0.098  2021        EST
166                 Ireland  0.2069  2021        IRL
167                  Greece  0.1305  2021        GRC
168                   Spain  0.1358  2021        ESP
169                  France  0.1289  2021        FRA
170                 Croatia  0.1003  2021        HRV
171                   Italy  0.1432  2021        ITA
172                  Cyprus  0.1276  2021        CYP
173                  Latvia  0.1024  2021        LVA
174               Lithuania  0.1003  2021        LTU
175              Luxembourg  0.1467  2021        LUX
176                 Hungary  0.0795  2021        HUN
177                   Malta  0.1209  2021        MLT
178             Netherlands  0.1351  2021        NLD
179                 Austria  0.1394  2021        AUT
180                  Poland  0.0921  2021        POL
181                Portugal  0.1131  2021        PRT
182                 Romania  0.1115  2021        ROU
183                Slovenia  0.1153  2021        SVN
184                Slovakia  0.1057  2021        SVK
185                 Finland    0.12  2021        FIN
186                  Sweden   0.134  2021        SWE
187                 Iceland   0.107  2021        ISL
188           Liechtenstein  0.1786  2021        LIE
189                  Norway  0.1326  2021        NOR
190          United Kingdom       :  2021        GBR
191  Bosnia and Herzegovina  0.0721  2021        BIH
192              Montenegro  0.0807  2021        MNE
193                 Moldova  0.0851  2021        MDA
194         North Macedonia  0.0713  2021        MKD
195                 Georgia  0.0535  2021        GEO
196                 Albania  0.0771  2021        ALB
197                  Serbia  0.0575  2021        SRB
198                 Türkiye  0.0672  2021        TUR
199                 Ukraine  0.0404  2021        UKR
200                 Belgium  0.2622  2022        BEL
201                Bulgaria  0.0911  2022        BGR
202                 Czechia  0.1879  2022        CZE
203                 Denmark  0.2371  2022        DNK
204                 Germany  0.1899  2022        DEU
205                 Estonia   0.159  2022        EST
206                 Ireland  0.2693  2022        IRL
207                  Greece   0.295  2022        GRC
208                   Spain  0.2579  2022        ESP
209                  France  0.1566  2022        FRA
210                 Croatia   0.106  2022        HRV
211                   Italy  0.2671  2022        ITA
212                  Cyprus  0.1693  2022        CYP
213                  Latvia  0.1779  2022        LVA
214               Lithuania  0.1205  2022        LTU
215              Luxembourg  0.1673  2022        LUX
216                 Hungary  0.0746  2022        HUN
217                   Malta  0.1221  2022        MLT
218             Netherlands  0.2187  2022        NLD
219                 Austria  0.1579  2022        AUT
220                  Poland  0.0912  2022        POL
221                Portugal  0.1688  2022        PRT
222                 Romania  0.1779  2022        ROU
223                Slovenia  0.1023  2022        SVN
224                Slovakia  0.1242  2022        SVK
225                 Finland  0.1335  2022        FIN
226                  Sweden  0.1815  2022        SWE
227                 Iceland  0.1205  2022        ISL
228           Liechtenstein  0.1898  2022        LIE
229                  Norway  0.2005  2022        NOR
230          United Kingdom       :  2022        GBR
231  Bosnia and Herzegovina  0.0733  2022        BIH
232              Montenegro  0.0792  2022        MNE
233                 Moldova  0.1047  2022        MDA
234         North Macedonia  0.0895  2022        MKD
235                 Georgia       :  2022        GEO
236                 Albania  0.0784  2022        ALB
237                  Serbia  0.0589  2022        SRB
238                 Türkiye  0.0748  2022        TUR
239                 Ukraine       :  2022        UKR
240                 Belgium  0.3592  2023        BEL
241                Bulgaria  0.0948  2023        BGR
242                 Czechia  0.2624  2023        CZE
243                 Denmark  0.2976  2023        DNK
244                 Germany  0.2973  2023        DEU
245                 Estonia  0.1666  2023        EST
246                 Ireland  0.4514  2023        IRL
247                  Greece  0.1876  2023        GRC
248                   Spain  0.2165  2023        ESP
249                  France  0.1893  2023        FRA
250                 Croatia   0.117  2023        HRV
251                   Italy   0.323  2023        ITA
252                  Cyprus  0.2312  2023        CYP
253                  Latvia  0.2521  2023        LVA
254               Lithuania  0.2407  2023        LTU
255              Luxembourg  0.3012  2023        LUX
256                 Hungary  0.0911  2023        HUN
257                   Malta  0.1186  2023        MLT
258             Netherlands  0.4436  2023        NLD
259                 Austria  0.2691  2023        AUT
260                  Poland  0.0918  2023        POL
261                Portugal  0.2983  2023        PRT
262                 Romania  0.1435  2023        ROU
263                Slovenia  0.1614  2023        SVN
264                Slovakia  0.1322  2023        SVK
265                 Finland  0.1934  2023        FIN
266                  Sweden  0.1784  2023        SWE
267                 Iceland  0.1208  2023        ISL
268           Liechtenstein  0.3888  2023        LIE
269                  Norway  0.1683  2023        NOR
270          United Kingdom       :  2023        GBR
271  Bosnia and Herzegovina  0.0742  2023        BIH
272              Montenegro  0.0845  2023        MNE
273                 Moldova  0.1795  2023        MDA
274         North Macedonia  0.0957  2023        MKD
275                 Georgia  0.0718  2023        GEO
276                 Albania  0.0842  2023        ALB
277                  Serbia  0.0686  2023        SRB
278                 Türkiye  0.0759  2023        TUR
279                 Ukraine       :  2023        UKR
280                 Belgium  0.2405  2024        BEL
281                Bulgaria  0.0989  2024        BGR
282                 Czechia  0.2574  2024        CZE
283                 Denmark  0.1883  2024        DNK
284                 Germany  0.2806  2024        DEU
285                 Estonia  0.1769  2024        EST
286                 Ireland  0.3856  2024        IRL
287                  Greece  0.1827  2024        GRC
288                   Spain  0.1841  2024        ESP
289                  France  0.2187  2024        FRA
290                 Croatia  0.1167  2024        HRV
291                   Italy  0.2451  2024        ITA
292                  Cyprus  0.2106  2024        CYP
293                  Latvia  0.2261  2024        LVA
294               Lithuania  0.1914  2024        LTU
295              Luxembourg  0.3024  2024        LUX
296                 Hungary  0.0861  2024        HUN
297                   Malta  0.1181  2024        MLT
298             Netherlands  0.2899  2024        NLD
299                 Austria  0.2946  2024        AUT
300                  Poland  0.1065  2024        POL
301                Portugal  0.1823  2024        PRT
302                 Romania  0.1392  2024        ROU
303                Slovenia  0.1684  2024        SVN
304                Slovakia   0.125  2024        SVK
305                 Finland  0.1763  2024        FIN
306                  Sweden  0.1571  2024        SWE
307                 Iceland  0.1345  2024        ISL
308           Liechtenstein  0.2811  2024        LIE
309                  Norway  0.1579  2024        NOR
310          United Kingdom       :  2024        GBR
311  Bosnia and Herzegovina  0.0724  2024        BIH
312              Montenegro  0.0894  2024        MNE
313                 Moldova  0.1359  2024        MDA
314         North Macedonia  0.0943  2024        MKD
315                 Georgia  0.0602  2024        GEO
316                 Albania  0.0929  2024        ALB
317                  Serbia  0.0783  2024        SRB
318                 Türkiye  0.0434  2024        TUR
319                 Ukraine       :  2024        UKR
320                 Belgium   0.179  2017        BEL
321                Bulgaria  0.0819  2017        BGR
322                 Czechia  0.1218  2017        CZE
323                 Denmark  0.0922  2017        DNK
324                 Germany  0.1383  2017        DEU
325                 Estonia   0.095  2017        EST
326                 Ireland  0.1865  2017        IRL
327                  Greece   0.109  2017        GRC
328                   Spain  0.1712  2017        ESP
329                  France  0.1132  2017        FRA
330                 Croatia  0.1012  2017        HRV
331                   Italy  0.1326  2017        ITA
332                  Cyprus   0.142  2017        CYP
333                  Latvia  0.1039  2017        LVA
334               Lithuania  0.0777  2017        LTU
335              Luxembourg   0.117  2017        LUX
336                 Hungary  0.0893  2017        HUN
337                   Malta  0.1221  2017        MLT
338             Netherlands  0.1152  2017        NLD
339                 Austria  0.1218  2017        AUT
340                  Poland   0.095  2017        POL
341                Portugal   0.108  2017        PRT
342                 Romania  0.0945  2017        ROU
343                Slovenia  0.1105  2017        SVN
344                Slovakia  0.0838  2017        SVK
345                 Finland  0.1064  2017        FIN
346                  Sweden  0.1305  2017        SWE
347                 Iceland    0.12  2017        ISL
348           Liechtenstein  0.1367  2017        LIE
349                  Norway  0.1137  2017        NOR
350          United Kingdom  0.1344  2017        GBR
351  Bosnia and Herzegovina  0.0724  2017        BIH
352              Montenegro  0.0806  2017        MNE
353                 Moldova  0.1013  2017        MDA
354         North Macedonia  0.0687  2017        MKD
355                 Georgia       :  2017        GEO
356                 Albania  0.0713  2017        ALB
357                  Serbia  0.0532  2017        SRB
358                 Türkiye  0.0773  2017        TUR
359                 Ukraine  0.0318  2017        UKR
360                 Belgium  0.1976  2018        BEL
361                Bulgaria  0.0838  2018        BGR
362                 Czechia  0.1299  2018        CZE
363                 Denmark  0.1116  2018        DNK
364                 Germany  0.1378  2018        DEU
365                 Estonia  0.1048  2018        EST
366                 Ireland  0.2006  2018        IRL
367                  Greece  0.1125  2018        GRC
368                   Spain  0.1947  2018        ESP
369                  France  0.1168  2018        FRA
370                 Croatia  0.1028  2018        HRV
371                   Italy  0.1416  2018        ITA
372                  Cyprus  0.1745  2018        CYP
373                  Latvia  0.1041  2018        LVA
374               Lithuania  0.0771  2018        LTU
375              Luxembourg  0.1302  2018        LUX

In [13]:
# Filters out all the rows containing a ':' in prices
electricity_data = electricity_data[electricity_data["Price"] != ":"]
electricity_data

                    Country   Price  Year countryISO
0                   Belgium  0.1929  2017        BEL
1                  Bulgaria  0.0796  2017        BGR
2                   Czechia  0.1176  2017        CZE
3                   Denmark   0.094  2017        DNK
4                   Germany  0.1389  2017        DEU
5                   Estonia  0.0926  2017        EST
6                   Ireland  0.1846  2017        IRL
7                    Greece  0.1139  2017        GRC
8                     Spain  0.1805  2017        ESP
9                    France  0.1089  2017        FRA
10                  Croatia  0.1011  2017        HRV
11                    Italy  0.1322  2017        ITA
12                   Cyprus  0.1454  2017        CYP
13                   Latvia  0.1043  2017        LVA
14                Lithuania  0.0783  2017        LTU
15               Luxembourg  0.1167  2017        LUX
16                  Hungary  0.0886  2017        HUN
17                    Malta   0.125  2017        MLT
18              Netherlands  0.1146  2017        NLD
19                  Austria  0.1221  2017        AUT
20                   Poland   0.096  2017        POL
21                 Portugal  0.1106  2017        PRT
22                  Romania  0.0871  2017        ROU
23                 Slovenia  0.1104  2017        SVN
24                 Slovakia  0.0832  2017        SVK
25                  Finland  0.1049  2017        FIN
26                   Sweden  0.1257  2017        SWE
27                  Iceland  0.1263  2017        ISL
28            Liechtenstein  0.1456  2017        LIE
29                   Norway  0.1163  2017        NOR
30           United Kingdom  0.1344  2017        GBR
31   Bosnia and Herzegovina   0.072  2017        BIH
32               Montenegro  0.0804  2017        MNE
33                  Moldova  0.0977  2017        MDA
34          North Macedonia  0.0695  2017        MKD
36                  Albania  0.0703  2017        ALB
37                   Serbia  0.0508  2017        SRB
38                  Türkiye  0.0845  2017        TUR
39                  Ukraine  0.0328  2017        UKR
40                  Belgium  0.1872  2018        BEL
41                 Bulgaria  0.0816  2018        BGR
42                  Czechia  0.1286  2018        CZE
43                  Denmark  0.1011  2018        DNK
44                  Germany  0.1379  2018        DEU
45                  Estonia  0.0989  2018        EST
46                  Ireland  0.1846  2018        IRL
47                   Greece  0.1132  2018        GRC
48                    Spain  0.1873  2018        ESP
49                   France  0.1134  2018        FRA
50                  Croatia   0.102  2018        HRV
51                    Italy  0.1285  2018        ITA
52                   Cyprus  0.1445  2018        CYP
53                   Latvia  0.1035  2018        LVA
54                Lithuania  0.0771  2018        LTU
55               Luxembourg  0.1283  2018        LUX
56                  Hungary  0.0885  2018        HUN
57                    Malta  0.1209  2018        MLT
58              Netherlands  0.1187  2018        NLD
59                  Austria  0.1232  2018        AUT
60                   Poland  0.0906  2018        POL
61                 Portugal  0.1007  2018        PRT
62                  Romania   0.099  2018        ROU
63                 Slovenia  0.1108  2018        SVN
64                 Slovakia  0.0942  2018        SVK
65                  Finland  0.1074  2018        FIN
66                   Sweden  0.1202  2018        SWE
67                  Iceland  0.1222  2018        ISL
68            Liechtenstein  0.1651  2018        LIE
69                   Norway  0.1254  2018        NOR
70           United Kingdom  0.1347  2018        GBR
71   Bosnia and Herzegovina  0.0722  2018        BIH
72               Montenegro  0.0828  2018        MNE
73                  Moldova   0.102  2018        MDA
74          North Macedonia  0.0662  2018        MKD
75                  Georgia   0.058  2018        GEO
77                   Serbia  0.0539  2018        SRB
78                  Türkiye  0.0727  2018        TUR
79                  Ukraine  0.0342  2018        UKR
80                  Belgium  0.1948  2019        BEL
81                 Bulgaria  0.0831  2019        BGR
82                  Czechia  0.1238  2019        CZE
83                  Denmark  0.1084  2019        DNK
84                  Germany  0.1473  2019        DEU
85                  Estonia  0.0982  2019        EST
86                  Ireland  0.2027  2019        IRL
87                   Greece  0.1141  2019        GRC
88                    Spain  0.1326  2019        ESP
89                   France  0.1148  2019        FRA
90                  Croatia  0.1028  2019        HRV
91                    Italy  0.1432  2019        ITA
92                   Cyprus  0.1545  2019        CYP
93                   Latvia  0.1136  2019        LVA
94                Lithuania  0.0947  2019        LTU
95               Luxembourg  0.1326  2019        LUX
96                  Hungary  0.0882  2019        HUN
97                    Malta  0.1214  2019        MLT
98              Netherlands  0.1357  2019        NLD
99                  Austria  0.1316  2019        AUT
100                  Poland  0.0898  2019        POL
101                Portugal  0.1181  2019        PRT
102                 Romania  0.0983  2019        ROU
103                Slovenia  0.1125  2019        SVN
104                Slovakia  0.0962  2019        SVK
105                 Finland  0.1173  2019        FIN
106                  Sweden  0.1297  2019        SWE
107                 Iceland  0.1131  2019        ISL
108           Liechtenstein   0.171  2019        LIE
109                  Norway   0.136  2019        NOR
110          United Kingdom   0.145  2019        GBR
111  Bosnia and Herzegovina  0.0729  2019        BIH
112              Montenegro  0.0834  2019        MNE
113                 Moldova  0.0936  2019        MDA
114         North Macedonia  0.0664  2019        MKD
115                 Georgia  0.0686  2019        GEO
116                 Albania  0.0767  2019        ALB
117                  Serbia  0.0541  2019        SRB
118                 Türkiye  0.0684  2019        TUR
119                 Ukraine  0.0369  2019        UKR
120                 Belgium  0.1872  2020        BEL
121                Bulgaria  0.0831  2020        BGR
122                 Czechia  0.1321  2020        CZE
123                 Denmark  0.0951  2020        DNK
124                 Germany   0.143  2020        DEU
125                 Estonia  0.0882  2020        EST
126                 Ireland  0.2037  2020        IRL
127                  Greece  0.1285  2020        GRC
128                   Spain  0.1178  2020        ESP
129                  France  0.1242  2020        FRA
130                 Croatia  0.1012  2020        HRV
131                   Italy  0.1382  2020        ITA
132                  Cyprus  0.1497  2020        CYP
133                  Latvia  0.0996  2020        LVA
134               Lithuania  0.1111  2020        LTU
135              Luxembourg  0.1465  2020        LUX
136                 Hungary  0.0812  2020        HUN
137                   Malta  0.1208  2020        MLT
138             Netherlands  0.1379  2020        NLD
139                 Austria  0.1358  2020        AUT
140                  Poland  0.0926  2020        POL
141                Portugal  0.1139  2020        PRT
142                 Romania  0.1045  2020        ROU
143                Slovenia  0.1063  2020        SVN
144                Slovakia  0.1074  2020        SVK
145                 Finland  0.1178  2020        FIN
146                  Sweden    0.12  2020        SWE
147                 Iceland  0.1061  2020        ISL
148           Liechtenstein  0.1823  2020        LIE
149                  Norway  0.0954  2020        NOR
150          United Kingdom  0.1532  2020        GBR
151  Bosnia and Herzegovina  0.0721  2020        BIH
152              Montenegro  0.0811  2020        MNE
153                 Moldova  0.1068  2020        MDA
154         North Macedonia  0.0662  2020        MKD
155                 Georgia  0.0562  2020        GEO
156                 Albania  0.0768  2020        ALB
157                  Serbia  0.0564  2020        SRB
158                 Türkiye  0.0805  2020        TUR
159                 Ukraine  0.0388  2020        UKR
160                 Belgium  0.1767  2021        BEL
161                Bulgaria  0.0853  2021        BGR
162                 Czechia  0.1284  2021        CZE
163                 Denmark   0.104  2021        DNK
164                 Germany  0.1562  2021        DEU
165                 Estonia   0.098  2021        EST
166                 Ireland  0.2069  2021        IRL
167                  Greece  0.1305  2021        GRC
168                   Spain  0.1358  2021        ESP
169                  France  0.1289  2021        FRA
170                 Croatia  0.1003  2021        HRV
171                   Italy  0.1432  2021        ITA
172                  Cyprus  0.1276  2021        CYP
173                  Latvia  0.1024  2021        LVA
174               Lithuania  0.1003  2021        LTU
175              Luxembourg  0.1467  2021        LUX
176                 Hungary  0.0795  2021        HUN
177                   Malta  0.1209  2021        MLT
178             Netherlands  0.1351  2021        NLD
179                 Austria  0.1394  2021        AUT
180                  Poland  0.0921  2021        POL
181                Portugal  0.1131  2021        PRT
182                 Romania  0.1115  2021        ROU
183                Slovenia  0.1153  2021        SVN
184                Slovakia  0.1057  2021        SVK
185                 Finland    0.12  2021        FIN
186                  Sweden   0.134  2021        SWE
187                 Iceland   0.107  2021        ISL
188           Liechtenstein  0.1786  2021        LIE
189                  Norway  0.1326  2021        NOR
191  Bosnia and Herzegovina  0.0721  2021        BIH
192              Montenegro  0.0807  2021        MNE
193                 Moldova  0.0851  2021        MDA
194         North Macedonia  0.0713  2021        MKD
195                 Georgia  0.0535  2021        GEO
196                 Albania  0.0771  2021        ALB
197                  Serbia  0.0575  2021        SRB
198                 Türkiye  0.0672  2021        TUR
199                 Ukraine  0.0404  2021        UKR
200                 Belgium  0.2622  2022        BEL
201                Bulgaria  0.0911  2022        BGR
202                 Czechia  0.1879  2022        CZE
203                 Denmark  0.2371  2022        DNK
204                 Germany  0.1899  2022        DEU
205                 Estonia   0.159  2022        EST
206                 Ireland  0.2693  2022        IRL
207                  Greece   0.295  2022        GRC
208                   Spain  0.2579  2022        ESP
209                  France  0.1566  2022        FRA
210                 Croatia   0.106  2022        HRV
211                   Italy  0.2671  2022        ITA
212                  Cyprus  0.1693  2022        CYP
213                  Latvia  0.1779  2022        LVA
214               Lithuania  0.1205  2022        LTU
215              Luxembourg  0.1673  2022        LUX
216                 Hungary  0.0746  2022        HUN
217                   Malta  0.1221  2022        MLT
218             Netherlands  0.2187  2022        NLD
219                 Austria  0.1579  2022        AUT
220                  Poland  0.0912  2022        POL
221                Portugal  0.1688  2022        PRT
222                 Romania  0.1779  2022        ROU
223                Slovenia  0.1023  2022        SVN
224                Slovakia  0.1242  2022        SVK
225                 Finland  0.1335  2022        FIN
226                  Sweden  0.1815  2022        SWE
227                 Iceland  0.1205  2022        ISL
228           Liechtenstein  0.1898  2022        LIE
229                  Norway  0.2005  2022        NOR
231  Bosnia and Herzegovina  0.0733  2022        BIH
232              Montenegro  0.0792  2022        MNE
233                 Moldova  0.1047  2022        MDA
234         North Macedonia  0.0895  2022        MKD
236                 Albania  0.0784  2022        ALB
237                  Serbia  0.0589  2022        SRB
238                 Türkiye  0.0748  2022        TUR
240                 Belgium  0.3592  2023        BEL
241                Bulgaria  0.0948  2023        BGR
242                 Czechia  0.2624  2023        CZE
243                 Denmark  0.2976  2023        DNK
244                 Germany  0.2973  2023        DEU
245                 Estonia  0.1666  2023        EST
246                 Ireland  0.4514  2023        IRL
247                  Greece  0.1876  2023        GRC
248                   Spain  0.2165  2023        ESP
249                  France  0.1893  2023        FRA
250                 Croatia   0.117  2023        HRV
251                   Italy   0.323  2023        ITA
252                  Cyprus  0.2312  2023        CYP
253                  Latvia  0.2521  2023        LVA
254               Lithuania  0.2407  2023        LTU
255              Luxembourg  0.3012  2023        LUX
256                 Hungary  0.0911  2023        HUN
257                   Malta  0.1186  2023        MLT
258             Netherlands  0.4436  2023        NLD
259                 Austria  0.2691  2023        AUT
260                  Poland  0.0918  2023        POL
261                Portugal  0.2983  2023        PRT
262                 Romania  0.1435  2023        ROU
263                Slovenia  0.1614  2023        SVN
264                Slovakia  0.1322  2023        SVK
265                 Finland  0.1934  2023        FIN
266                  Sweden  0.1784  2023        SWE
267                 Iceland  0.1208  2023        ISL
268           Liechtenstein  0.3888  2023        LIE
269                  Norway  0.1683  2023        NOR
271  Bosnia and Herzegovina  0.0742  2023        BIH
272              Montenegro  0.0845  2023        MNE
273                 Moldova  0.1795  2023        MDA
274         North Macedonia  0.0957  2023        MKD
275                 Georgia  0.0718  2023        GEO
276                 Albania  0.0842  2023        ALB
277                  Serbia  0.0686  2023        SRB
278                 Türkiye  0.0759  2023        TUR
280                 Belgium  0.2405  2024        BEL
281                Bulgaria  0.0989  2024        BGR
282                 Czechia  0.2574  2024        CZE
283                 Denmark  0.1883  2024        DNK
284                 Germany  0.2806  2024        DEU
285                 Estonia  0.1769  2024        EST
286                 Ireland  0.3856  2024        IRL
287                  Greece  0.1827  2024        GRC
288                   Spain  0.1841  2024        ESP
289                  France  0.2187  2024        FRA
290                 Croatia  0.1167  2024        HRV
291                   Italy  0.2451  2024        ITA
292                  Cyprus  0.2106  2024        CYP
293                  Latvia  0.2261  2024        LVA
294               Lithuania  0.1914  2024        LTU
295              Luxembourg  0.3024  2024        LUX
296                 Hungary  0.0861  2024        HUN
297                   Malta  0.1181  2024        MLT
298             Netherlands  0.2899  2024        NLD
299                 Austria  0.2946  2024        AUT
300                  Poland  0.1065  2024        POL
301                Portugal  0.1823  2024        PRT
302                 Romania  0.1392  2024        ROU
303                Slovenia  0.1684  2024        SVN
304                Slovakia   0.125  2024        SVK
305                 Finland  0.1763  2024        FIN
306                  Sweden  0.1571  2024        SWE
307                 Iceland  0.1345  2024        ISL
308           Liechtenstein  0.2811  2024        LIE
309                  Norway  0.1579  2024        NOR
311  Bosnia and Herzegovina  0.0724  2024        BIH
312              Montenegro  0.0894  2024        MNE
313                 Moldova  0.1359  2024        MDA
314         North Macedonia  0.0943  2024        MKD
315                 Georgia  0.0602  2024        GEO
316                 Albania  0.0929  2024        ALB
317                  Serbia  0.0783  2024        SRB
318                 Türkiye  0.0434  2024        TUR
320                 Belgium   0.179  2017        BEL
321                Bulgaria  0.0819  2017        BGR
322                 Czechia  0.1218  2017        CZE
323                 Denmark  0.0922  2017        DNK
324                 Germany  0.1383  2017        DEU
325                 Estonia   0.095  2017        EST
326                 Ireland  0.1865  2017        IRL
327                  Greece   0.109  2017        GRC
328                   Spain  0.1712  2017        ESP
329                  France  0.1132  2017        FRA
330                 Croatia  0.1012  2017        HRV
331                   Italy  0.1326  2017        ITA
332                  Cyprus   0.142  2017        CYP
333                  Latvia  0.1039  2017        LVA
334               Lithuania  0.0777  2017        LTU
335              Luxembourg   0.117  2017        LUX
336                 Hungary  0.0893  2017        HUN
337                   Malta  0.1221  2017        MLT
338             Netherlands  0.1152  2017        NLD
339                 Austria  0.1218  2017        AUT
340                  Poland   0.095  2017        POL
341                Portugal   0.108  2017        PRT
342                 Romania  0.0945  2017        ROU
343                Slovenia  0.1105  2017        SVN
344                Slovakia  0.0838  2017        SVK
345                 Finland  0.1064  2017        FIN
346                  Sweden  0.1305  2017        SWE
347                 Iceland    0.12  2017        ISL
348           Liechtenstein  0.1367  2017        LIE
349                  Norway  0.1137  2017        NOR
350          United Kingdom  0.1344  2017        GBR
351  Bosnia and Herzegovina  0.0724  2017        BIH
352              Montenegro  0.0806  2017        MNE
353                 Moldova  0.1013  2017        MDA
354         North Macedonia  0.0687  2017        MKD
356                 Albania  0.0713  2017        ALB
357                  Serbia  0.0532  2017        SRB
358                 Türkiye  0.0773  2017        TUR
359                 Ukraine  0.0318  2017        UKR
360                 Belgium  0.1976  2018        BEL
361                Bulgaria  0.0838  2018        BGR
362                 Czechia  0.1299  2018        CZE
363                 Denmark  0.1116  2018        DNK
364                 Germany  0.1378  2018        DEU
365                 Estonia  0.1048  2018        EST
366                 Ireland  0.2006  2018        IRL
367                  Greece  0.1125  2018        GRC
368                   Spain  0.1947  2018        ESP
369                  France  0.1168  2018        FRA
370                 Croatia  0.1028  2018        HRV
371                   Italy  0.1416  2018        ITA
372                  Cyprus  0.1745  2018        CYP
373                  Latvia  0.1041  2018        LVA
374               Lithuania  0.0771  2018        LTU
375              Luxembourg  0.1302  2018        LUX
376                 Hungary   0.088  2018        HUN
377                   Malta   0.123  2018        MLT
378             Netherlands  0.1212  2018        NLD
379                 Austria  0.1265  2018        AUT
380                  Poland  0.0889  2018        POL
381                Portugal  0.1028  2018        PRT
382                 Romania  0.0964  2018        ROU
383                Slovenia  0.1125  2018        SVN
384                Slovakia  0.0849  2018        SVK
385                 Finland  0.1144  2018        FIN
386                  Sweden   0.132  2018        SWE

In [14]:
#electricity_data.to_csv("Electricity Prices Cleaned.csv", index=False)