In [1]:
!pip install pandas pycountry-convert

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: pycountry-convert in /opt/anaconda3/lib/python3.12/site-packages (0.7.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: pprintpp>=0.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (0.4.0)
Requirement already satisfied: pycountry>=16.11.27.1 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (24.6.1)
Requirement already satisfied: pytest>=3.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (7.4.4)
Requirement already satisfied: pytest-mock>=1.6.3 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (3.14.0)
Requirement already satisfied: pytest-cov>=2.5.1 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (6.0.0)
Requirement already satisfied: repoze.lru>=0.7 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (0.7)
Requirement already satisfied: wheel>=0.30.0 in /opt/anaconda3/lib/python3.12/site-packages (from pycountry-convert) (0.43.0)
Requirement already satisfied: iniconfig in /opt/anaconda3/lib/python3.12/site-packages (from pytest>=3.4.0->pycountry-convert) (1.1.1)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from pytest>=3.4.0->pycountry-convert) (23.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in /opt/anaconda3/lib/python3.12/site-packages (from pytest>=3.4.0->pycountry-convert) (1.0.0)
Requirement already satisfied: coverage>=7.5 in /opt/anaconda3/lib/python3.12/site-packages (from coverage[toml]>=7.5->pytest-cov>=2.5.1->pycountry-convert) (7.6.8)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
# imports
import pandas as pd
import warnings
import pycountry_convert as PC
import pycountry
warnings.filterwarnings("ignore", category=FutureWarning)
# load the data
fuel_data = pd.read_excel('../Original Data/Fuel Prices Europe.xlsx', sheet_name=1)
fuel_data

,Consumer prices of petroleum products net of duties and taxes,CTR,EU_price_wo_tax_euro95,EU_price_wo_tax_diesel,EU_price_wo_tax_heEUing_oil,EU_price_wo_tax_fuel_oil_1,EU_price_wo_tax_fuel_oil_2,EU_price_wo_tax_LPG,CTR.1,EUR_price_wo_tax_euro95,...,SK_price_wo_tax_fuel_oil_2,SK_price_wo_tax_LPG,CTR.29,UK_exchange_rate,UK_price_wo_tax_euro95,UK_price_wo_tax_diesel,UK_price_wo_tax_heUKing_oil,UK_price_wo_tax_fuel_oil_1,UK_price_wo_tax_fuel_oil_2,UK_price_wo_tax_LPG
0,NaN,NaN,Euro-super 95 (I),Gas oil automobile Automotive gas oil Dieselkr...,Gas oil de chauffage Heating gas oil Heizöl (II),Fuel oil - Schweres Heizöl (III) Soufre,Fuel oil -Schweres Heizöl (III) Soufre > 1% S...,GPL pour moteur LPG motor fuel,NaN,Euro-super 95 (I),...,Fuel oil -Schweres Heizöl (III) Soufre > 1% S...,GPL pour moteur LPG motor fuel,NaN,NaN,Euro-super 95 (I),Gas oil automobile Automotive gas oil Dieselkr...,Gas oil de chauffage Heating gas oil Heizöl (II),Fuel oil - Schweres Heizöl (III) Soufre,Fuel oil -Schweres Heizöl (III) Soufre > 1% S...,GPL pour moteur LPG motor fuel
1,Date,NaN,1000 l,1000 l,1000 l,t,t,1000 l,NaN,1000 l,...,t,1000 l,NaN,NaN,1000 l,1000 l,1000 l,t,t,1000 l
2,2025-03-03 00:00:00,EU_,756.42887,818.598784,741.721554,677.074532,522.886994,503.461345,EUR_,755.386607,...,552.31,531.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-02-24 00:00:00,EU_,766.746871,828.204019,760.461851,647.151878,544.988386,506.008593,EUR_,765.172017,...,568.62,523.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-02-17 00:00:00,EU_,770.096355,829.144241,759.594147,682.06736,546.006504,505.825993,EUR_,768.579408,...,565,523.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,NaN,(IV),The prices inclusive of duties and taxes are V...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1027,NaN,The prices communicated by the Member States a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1029,NaN,Disclaimer: \nThis oil bulletin prepared by th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
fuel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Columns: 226 entries, Consumer prices of petroleum products net of duties and taxes to UK_price_wo_tax_LPG
dtypes: float64(15), object(211)
memory usage: 1.8+ MB

In [4]:
# country abbr map to change value names in country later
country_abbreviation = {
    "BE": "Belgium",
    "DE": "Germany",
    "DK": "Denmark",
    "LU": "Luxembourg",
    "NL": "Netherlands",
    "IE": "Ireland",
    "ES": "Spain",
    "PT": "Portugal",
    "IT": "Italy",
    "FR": "France",
    "GR": "Greece",
    "AT": "Austria",
    "SE": "Sweden",
    "FI": "Finland",
    "SI": "Slovenia",
    "LT": "Lithuania",
    "MT": "Malta",
    "CY": "Cyprus",
    "EE": "Estonia",
    "LV": "Latvia",
    "PL": "Poland",
    "CZ": "Czechia",
    "SK": "Slovakia",
    "HU": "Hungary",
    "BG": "Bulgaria",
    "RO": "Romania",
    "HR": "Croatia",
    "UK": "United Kingdom"
}

In [5]:
# Initial Data Proce
# Rename column to dates
fuel_data.rename(columns={'Consumer prices of petroleum products net of duties and taxes': 'Date'}, inplace=True)
# Drop rows containing NA/text values
fuel_data.drop([0, 1, 1029, 1028, 1006, 1007, 1008,1009,
               1010,1011,1012,1013, 1014, 1015, 1016, 1017,1018,1019,
                1020,1021,1022,1023,1024,1025,1026,1027], axis=0, inplace=True)
# convert date column to datetime format 
fuel_data["Date"] = pd.to_datetime(fuel_data["Date"])
# filter to only keep dates larger or equal to than 2017
fuel_data = fuel_data[fuel_data["Date"] >= "2017-01-02"]
# create year column and add the years from date column
fuel_data["Year"] = fuel_data["Date"].dt.year
# drops the date column as now we are using year column
fuel_data.drop("Date", axis=1, inplace=True)

/var/folders/1m/4nmbm9q96ng_6f_74_w1p90c0000gn/T/ipykernel_71670/2104709292.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_data["Year"] = fuel_data["Date"].dt.year
/var/folders/1m/4nmbm9q96ng_6f_74_w1p90c0000gn/T/ipykernel_71670/2104709292.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fuel_data.drop("Date", axis=1, inplace=True)

In [6]:
# Melting the data wide to long
# https://www.youtube.com/watch?v=F_N6oa1bksE&ab_channel=SelvaPrabhakaran%28ML%2B%
# Changes the data from wide to long format with Year as the ID and prices of petrol and diesel as values
# values (prices in this case) get stored in prices and value_vars get stored in Country_Type
fuel_melted = fuel_data.melt( 
                    id_vars=['Year'],
                    value_vars=[  
                        "AT_price_wo_tax_euro95", "BE_price_wo_tax_euro95", "BG_price_wo_tax_euro95", "CY_price_wo_tax_euro95",
                        "CZ_price_wo_tax_euro95", "DE_price_wo_tax_euro95", "DK_price_wo_tax_euro95", "EE_price_wo_tax_euro95",
                        "ES_price_wo_tax_euro95", "FI_price_wo_tax_euro95", "FR_price_wo_tax_euro95", "GR_price_wo_tax_euro95", 
                        "HR_price_wo_tax_euro95", "HU_price_wo_tax_euro95", "IE_price_wo_tax_euro95", "IT_price_wo_tax_euro95",
                        "LT_price_wo_tax_euro95", "LU_price_wo_tax_euro95", "LV_price_wo_tax_euro95", "MT_price_wo_tax_euro95",
                        "NL_price_wo_tax_euro95", "PL_price_wo_tax_euro95", "PT_price_wo_tax_euro95", "RO_price_wo_tax_euro95",
                        "SE_price_wo_tax_euro95", "SI_price_wo_tax_euro95", "SK_price_wo_tax_euro95", "UK_price_wo_tax_euro95",
                        "AT_price_wo_tax_diesel", "BE_price_wo_tax_diesel", "BG_price_wo_tax_diesel", "CY_price_wo_tax_diesel",
                        "CZ_price_wo_tax_diesel", "DE_price_wo_tax_diesel", "DK_price_wo_tax_diesel", "EE_price_wo_tax_diesel",
                        "ES_price_wo_tax_diesel", "FI_price_wo_tax_diesel", "FR_price_wo_tax_diesel", "GR_price_wo_tax_diesel", 
                        "HR_price_wo_tax_diesel", "HU_price_wo_tax_diesel", "IE_price_wo_tax_diesel", "IT_price_wo_tax_diesel",
                        "LT_price_wo_tax_diesel", "LU_price_wo_tax_diesel", "LV_price_wo_tax_diesel", "MT_price_wo_tax_diesel",
                        "NL_price_wo_tax_diesel", "PL_price_wo_tax_diesel", "PT_price_wo_tax_diesel", "RO_price_wo_tax_diesel",
                        "SE_price_wo_tax_diesel", "SI_price_wo_tax_diesel", "SK_price_wo_tax_diesel", "UK_price_wo_tax_diesel",
                    ],
                    var_name='Country_Type',  
                    value_name='Price')

In [7]:
fuel_melted

       Year            Country_Type   Price
0      2025  AT_price_wo_tax_euro95  682.05
1      2025  AT_price_wo_tax_euro95  700.38
2      2025  AT_price_wo_tax_euro95  699.55
3      2025  AT_price_wo_tax_euro95  698.72
4      2025  AT_price_wo_tax_euro95  692.05
...     ...                     ...     ...
23123  2017  UK_price_wo_tax_diesel  526.43
23124  2017  UK_price_wo_tax_diesel  514.66
23125  2017  UK_price_wo_tax_diesel   498.8
23126  2017  UK_price_wo_tax_diesel  497.76
23127  2017  UK_price_wo_tax_diesel   494.2

[23128 rows x 3 columns]

In [8]:
# https://stackoverflow.com/questions/37333299/splitting-a-pandas-dataframe-column-by-delimiter
# Splits the data by delimiter (underscore) and creates a new column to split the data into.
# .str[0] takes the first element after splitting by _ (country in this case) and adds it to the Country column
fuel_melted['Country'] = fuel_melted['Country_Type'].str.split('_').str[0]
# .str[4] takes the fith element after splitting by _ (fuel in this case) and adds it to the Fuel column
fuel_melted['Fuel'] = fuel_melted['Country_Type'].str.split('_').str[4]
# deletes the unwanted columns
fuel_melted.drop(['Country_Type'],axis=1, inplace=True)
# Renames the fuels to more readable format
fuel_melted['Fuel'] = fuel_melted['Fuel'].str.replace("euro95", "Petrol")
fuel_melted['Fuel'] = fuel_melted['Fuel'].str.replace("diesel", "Diesel")
# maps the country abbreviations to country names
fuel_melted['Country'] = fuel_melted['Country'].map(country_abbreviation)

fuel_melted

       Year   Price         Country    Fuel
0      2025  682.05         Austria  Petrol
1      2025  700.38         Austria  Petrol
2      2025  699.55         Austria  Petrol
3      2025  698.72         Austria  Petrol
4      2025  692.05         Austria  Petrol
...     ...     ...             ...     ...
23123  2017  526.43  United Kingdom  Diesel
23124  2017  514.66  United Kingdom  Diesel
23125  2017   498.8  United Kingdom  Diesel
23126  2017  497.76  United Kingdom  Diesel
23127  2017   494.2  United Kingdom  Diesel

[23128 rows x 4 columns]

In [9]:
# Referenced from https://stackoverflow.com/questions/47919846/using-pycountry-to-check-for-name-common-name-official-name
import pycountry
def get_country_code(name):
    for co in list(pycountry.countries):
        if name in co.name:
            return co.alpha_3
    return None

fuel_melted["countryISO"] = fuel_melted["Country"].apply(get_country_code)

In [10]:
# checks for any missing values in countryISO field
missing = fuel_melted['countryISO'].isna().sum()
print(f"{missing}")

0

In [11]:
fuel_melted.dropna(axis=0, inplace=True)

In [12]:
fuel_melted

       Year   Price         Country    Fuel countryISO
0      2025  682.05         Austria  Petrol        AUT
1      2025  700.38         Austria  Petrol        AUT
2      2025  699.55         Austria  Petrol        AUT
3      2025  698.72         Austria  Petrol        AUT
4      2025  692.05         Austria  Petrol        AUT
...     ...     ...             ...     ...        ...
23123  2017  526.43  United Kingdom  Diesel        GBR
23124  2017  514.66  United Kingdom  Diesel        GBR
23125  2017   498.8  United Kingdom  Diesel        GBR
23126  2017  497.76  United Kingdom  Diesel        GBR
23127  2017   494.2  United Kingdom  Diesel        GBR

[22696 rows x 5 columns]

In [13]:
# fuel_melted.to_csv("Fuel Prices Cleaned.csv", index=False)